# -*- coding: utf-8 -*-

# Reference: http://www-01.sil.org/iso639-3/download.asp

constructed = {"ido":"Ido",
               "tlh":"Klingon",
               "tzl":"Talossan",
               "jbo":"Lojban",
               "ina":"Interlingua",
               "epo":"Esperanto",
               # Additional constructed languages from http://linguistlist.org/forms/langs/GetListOfConstructedLgs.cfm
               "bzt": "Brithenig",
               "dws": "Dutton",
               "igs": "Interglossa",
               "ldn": "Láadan",
               "nov": "Novial",
               "occ": "Occidental",
               "qya": "Quenya",
               "rmv": "Romanova",
               "sjn": "Sindarin",
               "vol": "Volapük"}

retired_headings = ('Id', 'Ref_Name', 'Ret_Reason', 'Change_To', 'Ret_Remedy', 'Effective')

retired = [("fri", "Western Frisian", "C", "fry", "", "2007-02-01"),
					 ("auv", "Auvergnat", "M", "oci", "", "2007-03-14"),
					 ("gsc", "Gascon", "M", "oci", "", "2007-03-14"),
					 ("lms", "Limousin", "M", "oci", "", "2007-03-14"),
					 ("lnc", "Languedocien", "M", "oci", "", "2007-03-14"),
					 ("prv", "Provençal", "M", "oci", "", "2007-03-14"),
					 ("amd", "Amapá Creole", "N", "", "", "2007-07-18"),
					 ("bgh", "Bogan", "D", "bbh", "", "2007-07-18"),
					 ("bnh", "Banawá", "M", "jaa", "", "2007-07-18"),
					 ("bvs", "Belgian Sign Language", "S", "", "Split into Langue des signes de Belgique Francophone [sfb], and Vlaamse Gebarentaal [vgt]", "2007-07-18"),
					 ("ccy", "Southern Zhuang", "S", "", "Split into five languages: Nong Zhuang [zhn];  Yang Zhuang [zyg]; Yongnan Zhuang [zyn]; Zuojiang Zhuang [zzj]; Dai Zhuang [zhd].", "2007-07-18"),
					 ("cit", "Chittagonian", "S", "", "Split into Rohingya [rhg], and Chittagonian (new identifier [ctg])", "2007-07-18"),
					 ("flm", "Falam Chin", "S", "", "Split into Ranglong [rnl], and Falam Chin (new identifier [cfm]).", "2007-07-18"),
					 ("jap", "Jaruára", "M", "jaa", "", "2007-07-18"),
					 ("kob", "Kohoroxitari", "M", "xsu", "", "2007-07-18"),
					 ("mob", "Moinba", "S", "", "Split into five languages: Chug [cvg]; Lish [lsh];  Kalaktang Monpa [kkf]; Tawang Monpa [twm]; Sartang [onp]", "2007-07-18"),
					 ("mzf", "Aiku", "S", "", "Split into four languages: Ambrak [aag]; Yangum Dey [yde]; Yangum Gel [ygl]; Yangum Mon [ymo]", "2007-07-18"),
					 ("nhj", "Tlalitzlipa Nahuatl", "M", "nhi", "", "2007-07-18"),
					 ("nhs", "Southeastern Puebla Nahuatl", "S", "", "Split into Sierra Negra Nahuatl [nsu] and Southeastern Puebla Nahuatl [npl]", "2007-07-18"),
					 ("occ", "Occidental", "D", "ile", "", "2007-07-18"),
					 ("tmx", "Tomyang", "M", "ybi", "", "2007-07-18"),
					 ("tot", "Patla-Chicontla Totonac", "S", "", "Split into Upper Necaxa Totonac [tku] and Tecpatlán Totonac [tcw]", "2007-07-18"),
					 ("xmi", "Miarrã", "N", "", "", "2007-07-18"),
					 ("yib", "Yinglish", "M", "eng", "", "2007-07-18"),
					 ("ztc", "Lachirioag Zapotec", "M", "zty", "", "2007-07-18"),
					 ("atf", "Atuence", "N", "", "", "2007-08-10"),
					 ("bqe", "Navarro-Labourdin Basque", "M", "eus", "", "2007-08-10"),
					 ("bsz", "Souletin Basque", "M", "eus", "", "2007-08-10"),
					 ("aex", "Amerax", "M", "eng", "", "2008-01-14"),
					 ("ahe", "Ahe", "M", "knx", "", "2008-01-14"),
					 ("aiz", "Aari", "S", "", "Split into Aari [aiw] (new identifier) and Gayil [gyl]", "2008-01-14"),
					 ("akn", "Amikoana", "N", "", "", "2008-01-14"),
					 ("arf", "Arafundi", "S", "", "Split into three languages: Andai [afd]; Nanubae [afk]; Tapei [afp]", "2008-01-14"),
					 ("azr", "Adzera", "S", "", "Split into three languages: Adzera [adz] (new identifier), Sukurum [zsu] and Sarasira [zsa]", "2008-01-14"),
					 ("bcx", "Pamona", "S", "", "Split into Pamona [pmf] (new identifier) and Batui [zbt]", "2008-01-14"),
					 ("bii", "Bisu", "S", "", "Split into Bisu [bzi] (new identifier) and Laomian [lwm]", "2008-01-14"),
					 ("bke", "Bengkulu", "M", "pse", "", "2008-01-14"),
					 ("blu", "Hmong Njua", "S", "", "Split into four languages: Hmong Njua [hnj] (new identifier); Chuanqiandian Cluster Miao [cqd]; Horned Miao [hrm]; Small Flowery Miao [sfm]", "2008-01-14"),
					 ("boc", "Bakung Kenyah", "M", "xkl", "", "2008-01-14"),
					 ("bsd", "Sarawak Bisaya", "M", "bsb", "", "2008-01-14"),
					 ("bwv", "Bahau River Kenyah", "N", "", "", "2008-01-14"),
					 ("bxt", "Buxinhua", "D", "bgk", "", "2008-01-14"),
					 ("byu", "Buyang", "S", "", "Split into three languages: E'ma Buyang [yzg]; Langnian Buyang [yln]; Baha Buyang [yha]", "2008-01-14"),
					 ("ccx", "Northern Zhuang", "S", "", "Split into ten languages: Guibian Zh [zgn]; Liujiang Zh [zlj]; Qiubei Zh [zqe]; Guibei Zh [zgb]; Youjiang Zh [zyj]; Central Hongshuihe Zh [zch]; Eastern Hongshuihe Zh [zeh]; Liuqian Zh [zlq]; Yongbei Zh [zyb]; Lianshan Zh [zln].", "2008-01-14"),
					 ("cru", "Carútana", "M", "bwi", "", "2008-01-14"),
					 ("dat", "Darang Deng", "D", "mhu", "", "2008-01-14"),
					 ("dyk", "Land Dayak", "N", "", "", "2008-01-14"),
					 ("eni", "Enim", "M", "pse", "", "2008-01-14"),
					 ("fiz", "Izere", "S", "", "Split into Ganang [gne] and Izere [izr] (new identifier)", "2008-01-14"),
					 ("gen", "Geman Deng", "D", "mxj", "", "2008-01-14"),
					 ("ggh", "Garreh-Ajuran", "S", "", "Split between Borana [gax] and Somali [som]", "2008-01-14"),
					 ("itu", "Itutang", "M", "mzu", "", "2008-01-14"),
					 ("kds", "Lahu Shi", "S", "", "Split into Kucong [lkc] and Lahu Shi [lhi] (new identifier)", "2008-01-14"),
					 ("knh", "Kayan River Kenyah", "N", "", "", "2008-01-14"),
					 ("krg", "North Korowai", "M", "khe", "", "2008-01-14"),
					 ("krq", "Krui", "M", "ljp", "", "2008-01-14"),
					 ("kxg", "Katingan", "M", "nij", "", "2008-01-14"),
					 ("lmt", "Lematang", "M", "mui", "", "2008-01-14"),
					 ("lnt", "Lintang", "M", "pse", "", "2008-01-14"),
					 ("lod", "Berawan", "S", "", "Split into three languages: West Berawan [zbw], Central Berawan [zbc], and East Berawan [zbe]", "2008-01-14"),
					 ("mbg", "Northern Nambikuára", "S", "", "Split into six languages: Alapmunte [apv]; Lakondê [lkd]; Latundê [ltn]; Mamaindé [wmd]; Tawandê [xtw]; Yalakalore [xyl]", "2008-01-14"),
					 ("mdo", "Southwest Gbaya", "S", "", "Split into Southwest Gbaya [gso] (new identifier) and Gbaya-Mbodomo [gmm]", "2008-01-14"),
					 ("mhv", "Arakanese", "S", "", "Split into Marma [rmz] and Rakhine [rki]", "2008-01-14"),
					 ("miv", "Mimi", "M", "amj", "", "2008-01-14"),
					 ("mqd", "Madang", "M", "xkl", "", "2008-01-14"),
					 ("nky", "Khiamniungan Naga", "S", "", "Split into three languages: Khiamniungan Naga [kix] (new identifier); Para Naga [pzn]; Makuri Naga [jmn]", "2008-01-14"),
					 ("nxj", "Nyadu", "M", "byd", "", "2008-01-14"),
					 ("ogn", "Ogan", "M", "pse", "", "2008-01-14"),
					 ("ork", "Orokaiva", "S", "", "Split into Orokaiva [okv] (new identifier), Aeka [aez] and Hunjara-Kaina Ke [hkk]", "2008-01-14"),
					 ("paj", "Ipeka-Tapuia", "M", "kpc", "", "2008-01-14"),
					 ("pec", "Southern Pesisir", "M", "ljp", "", "2008-01-14"),
					 ("pen", "Penesak", "M", "mui", "", "2008-01-14"),
					 ("plm", "Palembang", "M", "mui", "", "2008-01-14"),
					 ("poj", "Lower Pokomo", "M", "pkb", "", "2008-01-14"),
					 ("pun", "Pubian", "M", "ljp", "", "2008-01-14"),
					 ("rae", "Ranau", "M", "ljp", "", "2008-01-14"),
					 ("rjb", "Rajbanshi", "S", "", "Split into Kamta (India) / Rangpuri (Bangladesh) [rkt] and Rajbanshi (Nepal) [rjs]", "2008-01-14"),
					 ("rws", "Rawas", "M", "mui", "", "2008-01-14"),
					 ("sdd", "Semendo", "M", "pse", "", "2008-01-14"),
					 ("sdi", "Sindang Kelingi", "M", "liw", "", "2008-01-14"),
					 ("skl", "Selako", "M", "knx", "", "2008-01-14"),
					 ("slb", "Kahumamahon Saluan", "M", "loe", "", "2008-01-14"),
					 ("srj", "Serawai", "M", "pse", "", "2008-01-14"),
					 ("suf", "Tarpia", "S", "", "Split into Tarpia [tpf] (new identifier) and Kaptiau [kbi]", "2008-01-14"),
					 ("suh", "Suba", "S", "", "Split into Suba [sxb] (Kenya) and Suba-Simbita [ssc] (Tanzania)", "2008-01-14"),
					 ("suu", "Sungkai", "M", "ljp", "", "2008-01-14"),
					 ("szk", "Sizaki", "M", "ikz", "", "2008-01-14"),
					 ("tle", "Southern Marakwet", "M", "enb", "", "2008-01-14"),
					 ("tnj", "Tanjong", "M", "kxn", "", "2008-01-14"),
					 ("ttx", "Tutong 1", "M", "bsb", "", "2008-01-14"),
					 ("ubm", "Upper Baram Kenyah", "N", "", "", "2008-01-14"),
					 ("vky", "Kayu Agung", "M", "kge", "", "2008-01-14"),
					 ("vmo", "Muko-Muko", "M", "min", "", "2008-01-14"),
					 ("wre", "Ware", "N", "", "", "2008-01-14"),
					 ("xah", "Kahayan", "M", "nij", "", "2008-01-14"),
					 ("xkm", "Mahakam Kenyah", "N", "", "", "2008-01-14"),
					 ("xuf", "Kunfal", "M", "awn", "", "2008-01-14"),
					 ("yio", "Dayao Yi", "M", "lpo", "", "2008-01-14"),
					 ("ymj", "Muji Yi", "S", "", "Split into five languages: Muji, Southern [ymc], Mojii [ymi], Qila Muji [ymq], Northern Muji [ymx], and Muzi [ymz]", "2008-01-14"),
					 ("ypl", "Pula Yi", "S", "", "Split into three languages: Phola [ypg], Phala [ypa] and Alo Phola [ypo]", "2008-01-14"),
					 ("ypw", "Puwa Yi", "S", "", "Split into three languages: Hlepho Phowa [yhl], Labo Phowa [ypb], and Ani Phowa [ypn]", "2008-01-14"),
					 ("ywm", "Wumeng Yi", "M", "ywu", "", "2008-01-14"),
					 ("yym", "Yuanjiang-Mojiang Yi", "S", "", "Split into Southern Nisu [nsd] and Southwestern Nisu [nsv]", "2008-01-14"),
					 ("mly", "Malay (individual language)", "S", "", "Split into four languages: Standard Malay [zsm], Haji [hji], Papuan Malay [pmy] and Malay (individual language) [zlm]", "2008-02-18"),
					 ("muw", "Mundari", "S", "", "Split into Munda [unx] and Mundari [unr] (new identifier)", "2008-02-18"),
					 ("xst", "Silt'e", "S", "", "Split into Wolane [wle] and Silt'e [stv] (new identifier)", "2008-02-28"),
					 ("ope", "Old Persian", "D", "peo", "", "2008-04-18"),
					 ("scc", "Serbian", "D", "srp", "", "2008-06-28"),
					 ("scr", "Croatian", "D", "hrv", "", "2008-06-28"),
					 ("xsk", "Sakan", "D", "kho", "", "2008-10-23"),
					 ("mol", "Moldavian", "M", "ron", "", "2008-11-03"),
					 ("aay", "Aariya", "N", "", "", "2009-01-16"),
					 ("acc", "Cubulco Achí", "M", "acr", "", "2009-01-16"),
					 ("cbm", "Yepocapa Southwestern Cakchiquel", "M", "cak", "", "2009-01-16"),
					 ("chs", "Chumash", "S", "", "Chumash is actually a family name, not a language name. Language family members already have code elements: Barbareño [boi], Cruzeño [crz], Ineseño [inz], Obispeño [obi], Purisimeño [puy], and Ventureño [veo]", "2009-01-16"),
					 ("ckc", "Northern Cakchiquel", "M", "cak", "", "2009-01-16"),
					 ("ckd", "South Central Cakchiquel", "M", "cak", "", "2009-01-16"),
					 ("cke", "Eastern Cakchiquel", "M", "cak", "", "2009-01-16"),
					 ("ckf", "Southern Cakchiquel", "M", "cak", "", "2009-01-16"),
					 ("cki", "Santa María De Jesús Cakchiquel", "M", "cak", "", "2009-01-16"),
					 ("ckj", "Santo Domingo Xenacoj Cakchiquel", "M", "cak", "", "2009-01-16"),
					 ("ckk", "Acatenango Southwestern Cakchiquel", "M", "cak", "", "2009-01-16"),
					 ("ckw", "Western Cakchiquel", "M", "cak", "", "2009-01-16"),
					 ("cnm", "Ixtatán Chuj", "M", "cac", "", "2009-01-16"),
					 ("cti", "Tila Chol", "M", "ctu", "", "2009-01-16"),
					 ("cun", "Cunén Quiché", "M", "quc", "", "2009-01-16"),
					 ("eml", "Emiliano-Romagnolo", "S", "", "Split into Emilian [egl] and Romagnol [rgn]", "2009-01-16"),
					 ("eur", "Europanto", "N", "", "", "2009-01-16"),
					 ("gmo", "Gamo-Gofa-Dawro", "S", "", "Split into three languages: Gamo [gmv], Gofa [gof], and Dawro [dwr]", "2009-01-16"),
					 ("hsf", "Southeastern Huastec", "M", "hus", "", "2009-01-16"),
					 ("hva", "San Luís Potosí Huastec", "M", "hus", "", "2009-01-16"),
					 ("ixi", "Nebaj Ixil", "M", "ixl", "", "2009-01-16"),
					 ("ixj", "Chajul Ixil", "M", "ixl", "", "2009-01-16"),
					 ("jai", "Western Jacalteco", "M", "jac", "", "2009-01-16"),
					 ("mms", "Southern Mam", "M", "mam", "", "2009-01-16"),
					 ("mpf", "Tajumulco Mam", "M", "mam", "", "2009-01-16"),
					 ("mtz", "Tacanec", "M", "mam", "", "2009-01-16"),
					 ("mvc", "Central Mam", "M", "mam", "", "2009-01-16"),
					 ("mvj", "Todos Santos Cuchumatán Mam", "M", "mam", "", "2009-01-16"),
					 ("poa", "Eastern Pokomam", "M", "poc", "", "2009-01-16"),
					 ("pob", "Western Pokomchí", "M", "poh", "", "2009-01-16"),
					 ("pou", "Southern Pokomam", "M", "poc", "", "2009-01-16"),
					 ("ppv", "Papavô", "N", "", "", "2009-01-16"),
					 ("quj", "Joyabaj Quiché", "M", "quc", "", "2009-01-16"),
					 ("qut", "West Central Quiché", "M", "quc", "", "2009-01-16"),
					 ("quu", "Eastern Quiché", "M", "quc", "", "2009-01-16"),
					 ("qxi", "San Andrés Quiché", "M", "quc", "", "2009-01-16"),
					 ("sic", "Malinguat", "S", "", "Split into Keak [keh] and Sos Kundi [sdk]", "2009-01-16"),
					 ("stc", "Santa Cruz", "S", "", "Split into Natügu [ntu] and Nalögo [nlz]", "2009-01-16"),
					 ("tlz", "Toala'", "M", "rob", "", "2009-01-16"),
					 ("tzb", "Bachajón Tzeltal", "M", "tzh", "", "2009-01-16"),
					 ("tzc", "Chamula Tzotzil", "M", "tzo", "", "2009-01-16"),
					 ("tze", "Chenalhó Tzotzil", "M", "tzo", "", "2009-01-16"),
					 ("tzs", "San Andrés Larrainzar Tzotzil", "M", "tzo", "", "2009-01-16"),
					 ("tzt", "Western Tzutujil", "M", "tzj", "", "2009-01-16"),
					 ("tzu", "Huixtán Tzotzil", "M", "tzo", "", "2009-01-16"),
					 ("tzz", "Zinacantán Tzotzil", "M", "tzo", "", "2009-01-16"),
					 ("vlr", "Vatrata", "S", "", "Split into Vera'a [vra] and Lemerig [lrz]", "2009-01-16"),
					 ("yus", "Chan Santa Cruz Maya", "M", "yua", "", "2009-01-16"),
					 ("nfg", "Nyeng", "M", "nfd", "", "2009-01-26"),
					 ("nfk", "Shakara", "M", "nfd", "", "2009-01-26"),
					 ("agp", "Paranan", "S", "", "Split into Pahanan Agta [apf] and Paranan [prf] (new identifier)", "2010-01-18"),
					 ("bhk", "Albay Bicolano", "S", "", "Split into Buhi'non Bikol [ubl]; Libon Bikol [lbl]; Miraya Bikol [rbl]; West Albay Bikol [fbl]", "2010-01-18"),
					 ("bkb", "Finallig", "S", "", "Split into Eastern Bontok [ebk] and Southern Bontok [obk]", "2010-01-18"),
					 ("btb", "Beti (Cameroon)", "S", "", "Beti is a group name, not an individual language name. Member languages are Bebele [beb], Bebil [bxp], Bulu [bum], Eton [eto], Ewondo [ewo], Fang [fan], and Mengisa [mct], all of which already have their own code elements.", "2010-01-18"),
					 ("cjr", "Chorotega", "M", "mom", "", "2010-01-18"),
					 ("cmk", "Chimakum", "D", "xch", "", "2010-01-18"),
					 ("drh", "Darkhat", "M", "khk", "", "2010-01-18"),
					 ("drw", "Darwazi", "M", "prs", "", "2010-01-18"),
					 ("gav", "Gabutamon", "M", "dev", "", "2010-01-18"),
					 ("mof", "Mohegan-Montauk-Narragansett", "S", "", "split into Mohegan-Pequot [xpq] and Narragansett [xnt]", "2010-01-18"),
					 ("mst", "Cataelano Mandaya", "M", "mry", "", "2010-01-18"),
					 ("myt", "Sangab Mandaya", "M", "mry", "", "2010-01-18"),
					 ("rmr", "Caló", "S", "", "split into Caló [rmq] and Erromintxela [emx]", "2010-01-18"),
					 ("sgl", "Sanglechi-Ishkashimi", "S", "", "split into Sanglechi [sgy] and Ishkashimi [isk]", "2010-01-18"),
					 ("sul", "Surigaonon", "S", "", "Split into Tandaganon [tgn] and Surigaonon [sgd] (new identifier)", "2010-01-18"),
					 ("sum", "Sumo-Mayangna", "S", "", "Split into Mayangna [yan] and Ulwa [ulw]", "2010-01-18"),
					 ("tnf", "Tangshewi", "M", "prs", "", "2010-01-18"),
					 ("wgw", "Wagawaga", "S", "", "Split into Yaleba [ylb] and Wagawaga [wgb] (new identifier)", "2010-01-18"),
					 ("ayx", "Ayi (China)", "D", "nun", "", "2011-05-18"),
					 ("bjq", "Southern Betsimisaraka Malagasy", "S", "", "split into Southern Betsimisaraka [bzc] and Tesaka Malagasy [tkg]", "2011-05-18"),
					 ("dha", "Dhanwar (India)", "N", "", "", "2011-05-18"),
					 ("dkl", "Kolum So Dogon", "S", "", "split into Ampari Dogon [aqd] and Mombo Dogon [dmb]", "2011-05-18"),
					 ("mja", "Mahei", "N", "", "", "2011-05-18"),
					 ("nbf", "Naxi", "S", "", "split into Naxi [nxq] and Narua [nru]", "2011-05-18"),
					 ("noo", "Nootka", "S", "", "Split into [dtd] Ditidaht and [nuk] Nuu-chah-nulth", "2011-05-18"),
					 ("tie", "Tingal", "M", "ras", "", "2011-05-18"),
					 ("tkk", "Takpa", "D", "twm", "", "2011-05-18"),
					 ("baz", "Tunen", "S", "", "Split Tunen [baz]  into Tunen [tvu] and Nyokon [nvo]", "2012-02-03"),
					 ("bjd", "Bandjigali", "M", "drl", "", "2012-02-03"),
					 ("ccq", "Chaungtha", "M", "rki", "", "2012-02-03"),
					 ("cka", "Khumi Awa Chin", "M", "cmr", "", "2012-02-03"),
					 ("dap", "Nisi (India)", "S", "", "Split into Nyishi [njz] and Tagin [tgj]", "2012-02-03"),
					 ("dwl", "Walo Kumbe Dogon", "S", "", "Split into Dogon, Bankan Tey (Walo) [dbw]  and Dogon, Ben Tey (Beni) [dbt]", "2012-02-03"),
					 ("elp", "Elpaputih", "N", "", "", "2012-02-03"),
					 ("gbc", "Garawa", "S", "", "Split into Garrwa [wrk] and Wanyi [wny]", "2012-02-03"),
					 ("gio", "Gelao", "S", "", "split into Qau [gqu] and A'ou [aou] with some going to Green Gelao [gig], some to Red Gelao [gir], and some to White Gelao [giw]", "2012-02-03"),
					 ("hrr", "Horuru", "M", "jal", "", "2012-02-03"),
					 ("ibi", "Ibilo", "M", "opa", "", "2012-02-03"),
					 ("jar", "Jarawa (Nigeria)", "S", "", "split into Gwak [jgk] and Bankal [jjr]", "2012-02-03"),
					 ("kdv", "Kado", "S", "", "split into Kadu [zkd] and Kanan [zkn]", "2012-02-03"),
					 ("kgh", "Upper Tanudan Kalinga", "M", "kml", "", "2012-02-03"),
					 ("kpp", "Paku Karen", "S", "", "Split into Paku Karen [jkp] and Mobwa Karen [jkm]", "2012-02-03"),
					 ("kzh", "Kenuzi-Dongola", "S", "", "Split into Andaandi (Dongolawi) [dgl] and Kenzi (Mattoki) [xnz]", "2012-02-03"),
					 ("lcq", "Luhu", "M", "ppr", "", "2012-02-03"),
					 ("mgx", "Omati", "S", "", "Split into Barikewa [jbk] and Mouwase [jmw]", "2012-02-03"),
					 ("nln", "Durango Nahuatl", "S", "", "Split into Eastern Durango Nahuatl [azd] and Western Durango Nahuatl [azn]", "2012-02-03"),
					 ("pbz", "Palu", "N", "", "", "2012-02-03"),
					 ("pgy", "Pongyong", "N", "", "", "2012-02-03"),
					 ("sca", "Sansu", "M", "sca", "", "2012-02-03"),
					 ("tlw", "South Wemale", "M", "weo", "", "2012-02-03"),
					 ("unp", "Worora", "S", "", "Split into Worrorra [wro] and Unggumi [xgu].", "2012-02-03"),
					 ("wiw", "Wirangu", "S", "", "Split into Wirangu [wgu] and Nauo [nwo]", "2012-02-03"),
					 ("ybd", "Yangbye", "M", "rki", "", "2012-02-03"),
					 ("yen", "Yendang", "S", "", "Split into Yendang [ynq] and Yotti [yot]", "2012-02-03"),
					 ("yma", "Yamphe", "M", "lrr", "", "2012-02-03"),
					 ("daf", "Dan", "S", "", "Split into Dan [dnj] and Kla-Dan [lda]", "2013-01-23"),
					 ("djl", "Djiwarli", "S", "", "Split into Djiwarli [dze] and Thiin [iin]", "2013-01-23"),
					 ("ggr", "Aghu Tharnggalu", "S", "", "Split into Aghu-Tharnggala [gtu], Gugu-Mini [ggm], and Ikarranggal [ikr]", "2013-01-23"),
					 ("ilw", "Talur", "M", "gal", "", "2013-01-23"),
					 ("izi", "Izi-Ezaa-Ikwo-Mgbo", "S", "", "Split into Izii [izz], Ezaa [eza], Ikwo [iqw], Mgbolizhia [gmz]", "2013-01-23"),
					 ("meg", "Mea", "M", "cir", "", "2013-01-23"),
					 ("mld", "Malakhel", "N", "", "", "2013-01-23"),
					 ("mnt", "Maykulan", "S", "", "Split into Mayi-Kulan [xyk], Mayi-Thakurti [xyt], Mayi-Yapi [xyj], and Wunumara [wnn]", "2013-01-23"),
					 ("mwd", "Mudbura", "S", "", "Split into Karranga [xrq] and Mudburra [dmw]", "2013-01-23"),
					 ("myq", "Forest Maninka", "N", "", "", "2013-01-23"),
					 ("nbx", "Ngura", "S", "", "Split into Eastern Karnic [ekc], Garlali [gll], Punthamara [xpt], Wangkumara [xwk], and Badjiri [jbi]", "2013-01-23"),
					 ("nlr", "Ngarla", "S", "", "Split into Ngarla [nrk] and Yinhawangka [ywg]", "2013-01-23"),
					 ("pcr", "Panang", "M", "adx", "", "2013-01-23"),
					 ("ppr", "Piru", "", "", "", "2013-01-23"),
					 ("tgg", "Tangga", "S", "", "Split into Fanamaket [bjp], Niwer Mil [hrc], and Warwar Feni [hrw]", "2013-01-23"),
					 ("wit", "Wintu", "S", "", "Split into Wintu [wnw], Nomlaki [nol], and Patwin [pwi]", "2013-01-23"),
					 ("xia", "Xiandao", "M", "acn", "", "2013-01-23"),
					 ("yiy", "Yir Yoront", "S", "", "Split into Yir Yoront [yyr] and Yirrk-Mel [yrm]", "2013-01-23"),
					 ("yos", "Yos", "M", "zom", "", "2013-01-23"),
					 ("emo", "Emok", "N", "", "", "2014-02-03"),
					 ("ggm", "Gugu Mini", "N", "", "", "2014-02-03"),
					 ("leg", "Lengua", "S", "", "Split into Enlhet [enl] and Enxet [enx]", "2014-02-03"),
					 ("lmm", "Lamam", "D", "lmm", "", "2014-02-03"),
					 ("mhh", "Maskoy Pidgin", "N", "", "", "2014-02-03"),
					 ("puz", "Purum Naga", "M", "pub", "", "2014-02-03"),
					 ("sap", "Sanapaná", "S", "", "Split into Sanapaná [spn] and Angaité [aqt]", "2014-02-03"),
					 ("yuu", "Yugh", "D", "yuu", "", "2014-02-03")]

retired_convert = {x[0]:x[3] for x in retired if len(x[3]) == 3}

dead = {"aaq": "Abnaki, Eastern",
        "abj": "Aka-Bea",
        "aci": "Aka-Cari",
        "ack": "Aka-Kora",
        "acl": "Akar-Bale",
        "acs": "Acroá",
        "aes": "Alsea",
        "aga": "Aguano",
        "aho": "Ahom",
        "ait": "Arikem",
        "ajw": "Ajawa",
        "akj": "Aka-Jeru",
        "akk": "Akkadian",
        "akm": "Aka-Bo",
        "akx": "Aka-Kede",
        "aky": "Aka-Kol",
        "ana": "Andaqui",
        "anb": "Andoa",
        "ang": "English, Old",
        "ans": "Anserma",
        "aoh": "Arma",
        "aqp": "Atakapa",
        "arc": "Aramaic, Official",
        "aru": "Aruá",
        "ash": "Abishira",
        "atc": "Atsahuaca",
        "auo": "Auyokawa",
        "ave": "Avestan",
        "avs": "Aushiri",
        "awk": "Awabakal",
        "axb": "Abipon",
        "axg": "Arára, Mato Grosso",
        "axm": "Armenian, Middle",
        "ayy": "Ayta, Tayabas",
        "bae": "Baré",
        "bjb": "Banggarla",
        "bjf": "Neo-Aramaic, Barzani Jewish",
        "bjy": "Bayali",
        "bll": "Biloxi",
        "bmn": "Bina",
        "boi": "Barbareño",
        "bow": "Rema",
        "bpb": "Barbacoas",
        "bqf": "Baga Kaloum",
        "brk": "Birked",
        "bsl": "Basa-Gumna",
        "bsv": "Baga Sobané",
        "bte": "Gamo-Ningi",
        "bue": "Beothuk",
        "bvv": "Baniva",
        "bxi": "Pirlatapa",
        "byg": "Baygo",
        "byq": "Basay",
        "byt": "Berti",
        "bzr": "Biri",
        "caj": "Chané",
        "caz": "Canichana",
        "cbe": "Chipiajes",
        "cbh": "Cagua",
        "cca": "Cauca",
        "ccr": "Cacaopera",
        "chb": "Chibcha",
        "chc": "Catawba",
        "chg": "Chagatai",
        "chs": "Chumash",
        "cht": "Cholón",
        "chu": "Slavonic, Old",
        "cid": "Chimariko",
        "cjr": "Chorotega",
        "cmg": "Mongolian, Classical",
        "cmk": "Chimakum",
        "cmm": "Michigamea",
        "cms": "Messapic",
        "cnx": "Cornish, Middle",
        "cob": "Chicomuceltec",
        "coj": "Cochimi",
        "cop": "Coptic",
        "coq": "Coquille",
        "coy": "Coyaima",
        "cpg": "Greek, Cappadocian",
        "crb": "Carib, Island",
        "crf": "Caramanta",
        "crr": "Algonquian, Carolina",
        "crz": "Cruzeño",
        "csi": "Miwok, Coast",
        "css": "Ohlone, Southern",
        "cst": "Ohlone, Northern",
        "ctm": "Chitimacha",
        "cum": "Cumeral",
        "cuo": "Cumanagoto",
        "cyb": "Cayubaba",
        "czk": "Knaanic",
        "dcr": "Negerhollands",
        "dep": "Delaware, Pidgin",
        "dgn": "Dagoman",
        "dhu": "Dhurga",
        "dif": "Dieri",
        "dlm": "Dalmatian",
        "drq": "Dura",
        "drr": "Dororo",
        "dum": "Dutch, Middle",
        "duy": "Agta, Dicamay",
        "duz": "Duli",
        "ecr": "Eteocretan",
        "ecy": "Eteocypriot",
        "egy": "Egyptian",
        "elx": "Elamite",
        "emm": "Mamulique",
        "emo": "Emok",
        "emy": "Mayan, Epigraphic",
        "enm": "English, Middle",
        "esm": "Esuma",
        "esq": "Esselen",
        "etc": "Etchemin",
        "ett": "Etruscan",
        "fos": "Siraya",
        "frk": "Frankish",
        "frm": "French, Middle",
        "fro": "French, Old",
        "gce": "Galice",
        "gez": "Geez",
        "gft": "Gafat",
        "ggk": "Kungarakany",
        "ggr": "Aghu Tharnggalu",
        "ghc": "Gaelic, Hiberno-Scottish",
        "gho": "Ghomara",
        "gli": "Guliguli",
        "glv": "Manx",
        "gly": "Gule",
        "gmh": "German, Middle High",
        "gml": "German, Middle Low",
        "gmy": "Greek, Mycenaean",
        "gnc": "Guanche",
        "gnl": "Gangulu",
        "gnr": "Gureng Gureng",
        "goh": "German, Old High",
        "got": "Gothic",
        "gqn": "Guana",
        "grc": "Greek, Ancient",
        "guv": "Gey",
        "gvy": "Guyani",
        "hbo": "Hebrew, Ancient",
        "hib": "Hibito",
        "hit": "Hittite",
        "hlu": "Luwian, Hieroglyphic",
        "hmk": "Maek",
        "hom": "Homa",
        "hor": "Horo",
        "htx": "Hittite, Middle",
        "iff": "Ifo",
        "iml": "Miluk",
        "ims": "Marsian",
        "imy": "Milyan",
        "inm": "Minaean",
        "inz": "Ineseño",
        "iow": "Iowa-Oto",
        "ite": "Itene",
        "jgb": "Ngbee",
        "jor": "Jorá",
        "jpa": "Aramaic, Jewish Palestinian",
        "juc": "Jurchen",
        "kae": "Ketangalan",
        "kaw": "Kawi",
        "kba": "Kalarko",
        "kbf": "Kakauhua",
        "kda": "Worimi",
        "kgg": "Kusunda",
        "kgm": "Karipúna",
        "kii": "Kitsai",
        "koc": "Kpati",
        "kof": "Kubi",
        "kox": "Coxima",
        "kpn": "Kepkiriwát",
        "kqu": "Seroa",
        "krb": "Karkin",
        "ktg": "Kalkutung",
        "ktk": "Kaniet",
        "ktq": "Katabaga",
        "kuz": "Kunza",
        "kwz": "Kwadi",
        "kxo": "Kanoé",
        "kzk": "Kazukuru",
        "kzw": "Karirí-Xocó",
        "lab": "Linear A",
        "lat": "Latin",
        "laz": "Aribwatsa",
        "lhs": "Mlahsö",
        "llf": "Hermit",
        "lmz": "Lumbee",
        "lng": "Langobardic",
        "lnj": "Leningitij",
        "lre": "Laurentian",
        "ltc": "Chinese, Late Middle",
        "mbe": "Molale",
        "mcl": "Macaguaje",
        "mfw": "Mulaha",
        "mga": "Irish, Middle",
        "mia": "Miami",
        "mje": "Muskum",
        "mjy": "Mahican",
        "mkq": "Miwok, Bay",
        "mnt": "Maykulan",
        "mod": "Mobilian",
        "mof": "Mohegan-Montauk-Narragansett",
        "mom": "Mangue",
        "msp": "Maritsauá",
        "mtm": "Mator",
        "mtn": "Matagalpa",
        "mvb": "Mattole",
        "mvl": "Mbara",
        "mwu": "Mittu",
        "mxi": "Mozarabic",
        "mys": "Mesmes",
        "myz": "Mandaic, Classical",
        "nay": "Narrinyeri",
        "nci": "Nahuatl, Classical",
        "ncz": "Natchez",
        "ndf": "Nadruvian",
        "nei": "Hittite, Neo-",
        "ngv": "Nagumi",
        "nhc": "Nahuatl, Tabasco",
        "nid": "Ngandi",
        "nkp": "Niuatoputapu",
        "nnt": "Nanticoke",
        "nok": "Nooksack",
        "nom": "Nocamán",
        "non": "Norse, Old",
        "nrc": "Noric",
        "nrn": "Norn",
        "nrp": "Picene, North",
        "nrt": "Kalapuya, Northern",
        "nts": "Natagaimas",
        "ntw": "Nottoway",
        "nuc": "Nukuini",
        "nwa": "Nawathinehena",
        "nwx": "Newar, Middle",
        "nwy": "Nottoway-Meherrin",
        "nxm": "Numidian",
        "nyp": "Nyang'i",
        "nyx": "Nganyaywana",
        "oar": "Aramaic, Old",
        "oav": "Avar, Old",
        "obi": "Obispeño",
        "obm": "Moabite",
        "obr": "Burmese, Old",
        "obt": "Breton, Old",
        "och": "Chinese, Old",
        "oco": "Cornish, Old",
        "odt": "Dutch, Old",
        "ofo": "Ofo",
        "ofs": "Frisian, Old",
        "oge": "Georgian, Old",
        "oht": "Hittite, Old",
        "ohu": "Hungarian, Old",
        "ojp": "Japanese, Old",
        "okj": "Oko-Juwoi",
        "okm": "Korean, Middle",
        "oko": "Korean, Old",
        "omc": "Mochica",
        "ome": "Omejes",
        "omk": "Omok",
        "omn": "Minoan",
        "omp": "Manipuri, Old",
        "omr": "Marathi, Old",
        "omu": "Omurano",
        "omx": "Mon, Old",
        "onw": "Nubian, Old",
        "oos": "Ossetic, Old",
        "opy": "Ofayé",
        "orv": "Russian, Old",
        "osc": "Oscan",
        "osp": "Spanish, Old",
        "osx": "Saxon, Old",
        "otb": "Tibetan, Old",
        "oti": "Oti",
        "otk": "Turkish, Old",
        "otu": "Otuke",
        "oty": "Tamil, Old",
        "oui": "Uighur, Old",
        "oum": "Ouma",
        "owl": "Welsh, Old",
        "paf": "Paranawát",
        "pal": "Pahlavi",
        "pax": "Pankararé",
        "paz": "Pankararú",
        "peb": "Pomo, Eastern",
        "pej": "Pomo, Northern",
        "peo": "Persian, Old",
        "pgn": "Paelignian",
        "phn": "Phoenician",
        "pie": "Piro",
        "pij": "Pijao",
        "pim": "Powhatan",
        "pka": "Prākrit, Ardhamāgadhī",
        "pkc": "Paekche",
        "pli": "Pali",
        "plq": "Palaic",
        "pmc": "Palumata",
        "pmh": "Prākrit, Māhārāṣṭri",
        "pmk": "Pamlico",
        "pml": "Lingua Franca",
        "pmz": "Pame, Southern",
        "pno": "Panobo",
        "pod": "Ponares",
        "pog": "Potiguára",
        "pox": "Polabian",
        "ppu": "Papora",
        "prg": "Prussian",
        "pro": "Provençal, Old",
        "prr": "Puri",
        "psu": "Prākrit, Sauraseni",
        "psy": "Piscataway",
        "pth": "Pataxó Hã-Ha-Hãe",
        "ptw": "Pentlatch",
        "puq": "Puquina",
        "puy": "Purisimeño",
        "pyx": "Pyu",
        "qey": "Sam'alian",
        "qgg": "Ammonite",
        "qgk": "Middle Greek",
        "qgu": "Wulguru",
        "qkn": "Old Kannada",
        "qok": "Old Khmer",
        "qpp": "Paisaci Prakrit",
        "qwc": "Quechua, Classical",
        "qwm": "Kuman",
        "qwt": "Kwalhioqua-Tlatskanai",
        "rem": "Remo",
        "rna": "Runa",
        "sam": "Aramaic, Samaritan",
        "sar": "Saraveca",
        "sbv": "Sabine",
        "scx": "Sicel",
        "sds": "Sened",
        "sdt": "Shuadit",
        "sga": "Irish, Old",
        "sgm": "Singa",
        "sis": "Siuslaw",
        "sjk": "Sami, Kemi",
        "sjs": "Senhaja De Srair",
        "skw": "Creole Dutch, Skepi",
        "sln": "Salinan",
        "smp": "Samaritan",
        "snh": "Shinabo",
        "sni": "Sensi",
        "sog": "Sogdian",
        "spx": "Picene, South",
        "sqn": "Susquehannock",
        "sut": "Subtiaba",
        "sux": "Sumerian",
        "svx": "Skalvian",
        "sxc": "Sicanian",
        "sxk": "Kalapuya, Southern",
        "sxl": "Selian",
        "sxo": "Sorothaptic",
        "syc": "Syriac, Classical",
        "szd": "Seru",
        "tas": "Tay Boi",
        "tbb": "Tapeba",
        "tbh": "Thurawal",
        "tbu": "Tubar",
        "teb": "Tetete",
        "ten": "Tama",
        "tep": "Tepecano",
        "tgv": "Tingui-Boto",
        "tgy": "Togoyo",
        "til": "Tillamook",
        "tjm": "Timucua",
        "tjn": "Tonjon",
        "tju": "Tjurruru",
        "tka": "Truká",
        "tkf": "Tukumanféd",
        "tkm": "Takelma",
        "tmg": "Ternateño",
        "tmr": "Aramaic, Jewish Babylonian",
        "tmz": "Tamanaku",
        "tnq": "Taino",
        "tnx": "Tanema",
        "toe": "Tomedes",
        "tpk": "Tupinikin",
        "tpn": "Tupinambá",
        "tpw": "Tupí",
        "tqr": "Torona",
        "tqw": "Tonkawa",
        "try": "Turung",
        "tta": "Tutelo",
        "ttk": "Totoro",
        "tud": "Tuxá",
        "tun": "Tunica",
        "tux": "Tuxináwa",
        "tvy": "Pidgin, Timor",
        "twa": "Twana",
        "twc": "Teshenawa",
        "twt": "Turiwára",
        "txb": "Tokharian B",
        "txc": "Tsetsaut",
        "txg": "Tangut",
        "txh": "Thracian",
        "txr": "Tartessian",
        "uam": "Uamué",
        "uby": "Ubykh",
        "uga": "Ugaritic",
        "umc": "Marrucinian",
        "umo": "Umotína",
        "unm": "Unami",
        "uru": "Urumi",
        "urv": "Uruava",
        "uun": "Kulon-Pazeh",
        "veo": "Ventureño",
        "vka": "Kariyarra",
        "vkm": "Kamakan",
        "vml": "Malgana",
        "vms": "Moksela",
        "vmv": "Maidu, Valley",
        "vnk": "Vano",
        "waf": "Wakoná",
        "wam": "Wampanoag",
        "wir": "Wiraféd",
        "wiy": "Wiyot",
        "wka": "Kw'adza",
        "wlk": "Wailaki",
        "wlm": "Welsh, Middle",
        "wlu": "Wuliwuli",
        "wma": "Mawa",
        "wmn": "Waamwang",
        "wnd": "Wandarang",
        "woy": "Weyto",
        "wri": "Wariyangga",
        "wrw": "Gugu Warra",
        "wsu": "Wasu",
        "wur": "Wurrugu",
        "wya": "Wyandot",
        "xaa": "Arabic, Andalusian",
        "xad": "Adai",
        "xae": "Aequian",
        "xag": "Aghwan",
        "xai": "Kaimbé",
        "xam": "/Xam",
        "xap": "Apalachee",
        "xaq": "Aquitanian",
        "xar": "Karami",
        "xas": "Kamas",
        "xba": "Kamba",
        "xbc": "Bactrian",
        "xbm": "Breton, Middle",
        "xbo": "Bolgarian",
        "xbw": "Kambiwá",
        "xcb": "Cumbric",
        "xcc": "Camunic",
        "xce": "Celtiberian",
        "xcg": "Gaulish, Cisalpine",
        "xch": "Chimakum",
        "xcl": "Armenian, Classical",
        "xcm": "Comecrudo",
        "xcn": "Cotoname",
        "xco": "Chorasmian",
        "xcr": "Carian",
        "xct": "Tibetan, Classical",
        "xcu": "Curonian",
        "xcv": "Chuvantsy",
        "xcw": "Coahuilteco",
        "xcy": "Cayuse",
        "xdc": "Dacian",
        "xdm": "Edomite",
        "xdr": "Deir Alla",
        "xeb": "Eblan",
        "xeg": "//Xegwi",
        "xep": "Epi-Olmec",
        "xfa": "Faliscan",
        "xga": "Galatian",
        "xgf": "Gabrielino-Fernandeño",
        "xgl": "Galindan",
        "xgr": "Garza",
        "xha": "Harami",
        "xhc": "Hunnic",
        "xhd": "Hadrami",
        "xhr": "Hernican",
        "xht": "Hattic",
        "xhu": "Hurrian",
        "xib": "Iberian",
        "xil": "Illyrian",
        "xin": "Xinca",
        "xiv": "Indus Valley Language",
        "xkr": "Xakriabá",
        "xlb": "Loup B",
        "xlc": "Lycian",
        "xld": "Lydian",
        "xle": "Lemnian",
        "xlg": "Ligurian",
        "xli": "Liburnian",
        "xln": "Alanic",
        "xlo": "Loup A",
        "xlp": "Lepontic",
        "xls": "Lusitanian",
        "xlu": "Luwian, Cuneiform",
        "xly": "Elymian",
        "xme": "Median",
        "xmk": "Macedonian, Ancient",
        "xmn": "Persian, Manichaean Middle",
        "xmr": "Meroitic",
        "xna": "North Arabian, Ancient",
        "xng": "Mongolian, Middle",
        "xno": "Anglo-Norman",
        "xoo": "Xukurú",
        "xpc": "Pecheneg",
        "xpg": "Phrygian",
        "xpi": "Pictish",
        "xpm": "Pumpokol",
        "xpn": "Kapinawá",
        "xpo": "Pochutec",
        "xpp": "Puyo-Paekche",
        "xpr": "Parthian",
        "xps": "Pisidian",
        "xpu": "Punic",
        "xpy": "Puyo",
        "xqa": "Karakhanid",
        "xqt": "Qatabanian",
        "xrm": "Armazic",
        "xrn": "Arin",
        "xrr": "Raetic",
        "xrt": "Aranama-Tamique",
        "xsa": "Sabaean",
        "xsc": "Scythian",
        "xsd": "Sidetic",
        "xsk": "Sakan",
        "xso": "Solano",
        "xss": "Assan",
        "xsv": "Sudovian",
        "xtg": "Gaulish, Transalpine",
        "xto": "Tokharian A",
        "xtq": "Tumshuqese",
        "xtr": "Tripuri, Early",
        "xtz": "Tasmanian",
        "xum": "Umbrian",
        "xup": "Umpqua, Upper",
        "xur": "Urartian",
        "xve": "Venetic",
        "xvn": "Vandalic",
        "xvo": "Volscian",
        "xvs": "Vestinian",
        "xwc": "Woccon",
        "xwo": "Oirat, Written",
        "xzh": "Zhang-Zhung",
        "xzm": "Zemgalian",
        "xzp": "Zapotec, Ancient",
        "ybn": "Yabaâna",
        "yei": "Yeni",
        "ylr": "Yalarnnga",
        "yme": "Yameo",
        "yms": "Mysian",
        "ymt": "Mator-Taygi-Karagas",
        "ynn": "Yana",
        "ynu": "Yahuna",
        "yob": "Yoba",
        "ysc": "Yassic",
        "ysr": "Yupik, Sirenik",
        "yub": "Yugambal",
        "yug": "Yug",
        "yvt": "Yavitero",
        "zkb": "Koibal",
        "zkg": "Koguryo",
        "zkh": "Khorezmian",
        "zkk": "Karankawa",
        "zko": "Kott",
        "zkt": "Kitan",
        "zku": "Kaurna",
        "zkv": "Krevinian",
        "zkz": "Khazar",
        "znk": "Manangkari",
        "zra": "Kara",
        "zrp": "Zarphatic",
        "zsk": "Kaskean"}

macro_split = {"aka": {"fat": "Fanti", "twi": "Twi"},
               "ara": {"aao": "Algerian Saharan Arabic", "abh": "Tajiki Arabic", "abv": "Baharna Arabic", "acm": "Mesopotamian Arabic", "acq": "Ta'izzi-Adeni Arabic", "acw": "Hijazi Arabic", "acx": "Omani Arabic", "acy": "Cypriot Arabic", "adf": "Dhofari Arabic", "aeb": "Tunisian Arabic", "aec": "Saidi Arabic", "afb": "Gulf Arabic", "ajp": "South Levantine Arabic", "apc": "North Levantine Arabic", "apd": "Sudanese Arabic", "arb": "Standard Arabic", "arq": "Algerian Arabic", "ars": "Najdi Arabic", "ary": "Moroccan Arabic", "arz": "Egyptian Arabic", "auz": "Uzbeki Arabic", "avl": "Eastern Egyptian Bedawi Arabic", "ayh": "Hadrami Arabic", "ayl": "Libyan Arabic", "ayn": "Sanaani Arabic", "ayp": "North Mesopotamian Arabic", "bbz": "Babalia Creole Arabic", "pga": "Sudanese Creole Arabic", "shu": "Chadian Arabic", "ssh": "Shihhi Arabic"},
               "aym": {"ayc": "Southern Aymara", "ayr": "Central Aymara"},
               "aze": {"azb": "South Azerbaijani", "azj": "North Azerbaijani"},
               "bal": {"bcc": "Southern Balochi", "bgn": "Western Balochi", "bgp": "Eastern Balochi"},
               "bik": {"bcl": "Central Bikol", "bhk": "Albay Bicolano  (Retired 1/15/2010)", "bln": "Southern Catanduanes Bikol", "bto": "Rinconada Bikol", "cts": "Northern Catanduanes Bikol", "fbl": "West Albay Bikol", "lbl": "Libon Bikol", "rbl": "Miraya Bikol", "ubl": "Buhi'non Bikol"},
               "bnc": {"ebk": "Eastern Bontok", "lbk": "Central Bontok", "obk": "Southern Bontok", "rbk": "Northern Bontok", "vbk": "Southwestern Bontok"},
               "bua": {"bxm": "Mongolia Buriat", "bxr": "Russia Buriat", "bxu": "China Buriat"},
               "chm": {"mhr": "Eastern Mari", "mrj": "Western Mari"},
               "cre": {"crj": "Southern East Cree", "crk": "Plains Cree", "crl": "Northern East Cree", "crm": "Moose Cree", "csw": "Swampy Cree", "cwd": "Woods Cree"},
               "del": {"umu": "Munsee", "unm": "Unami"},
               "den": {"scs": "North Slavey", "xsl": "South Slavey"},
               "din": {"dib": "South Central Dinka", "dik": "Southwestern Dinka", "dip": "Northeastern Dinka", "diw": "Northwestern Dinka", "dks": "Southeastern Dinka"},
               "doi": {"dgo": "Dogri (individual language)", "xnr": "Kangri"},
               "est": {"ekk": "Standard Estonian", "vro": "Võro"},
               "fas": {"pes": "Iranian Persian", "prs": "Dari"},
               "ful": {"ffm": "Maasina Fulfulde", "fub": "Adamawa Fulfulde", "fuc": "Pulaar", "fue": "Borgu Fulfulde", "fuf": "Pular", "fuh": "Western Niger Fulfulde", "fui": "Bagirmi Fulfulde", "fuq": "Central-Eastern Niger Fulfulde", "fuv": "Nigerian Fulfulde"},
               "gba": {"bdt": "Bokoto", "gbp": "Gbaya-Bossangoa", "gbq": "Gbaya-Bozoum", "gmm": "Gbaya-Mbodomo", "gso": "Southwest Gbaya", "gya": "Northwest Gbaya", "mdo": "Southwest Gbaya  (Retired 1/14/2008)"},
               "gon": {"ggo": "Southern Gondi", "gno": "Northern Gondi"},
               "grb": {"gbo": "Northern Grebo", "gec": "Gboloo Grebo", "grj": "Southern Grebo", "grv": "Central Grebo", "gry": "Barclayville Grebo"},
               "grn": {"gnw": "Western Bolivian Guaraní", "gug": "Paraguayan Guaraní", "gui": "Eastern Bolivian Guaraní", "gun": "Mbyá Guaraní", "nhd": "Chiripá"},
               "hai": {"hax": "Southern Haida", "hdn": "Northern Haida"},
               "hbs": {"bos": "Bosnian", "hrv": "Croatian", "srp": "Serbian"},
               "hmn": {"blu": "Hmong Njua  (Retired 1/14/2008)", "cqd": "Chuanqiandian Cluster Miao", "hea": "Northern Qiandong Miao", "hma": "Southern Mashan Hmong", "hmc": "Central Huishui Hmong", "hmd": "Large Flowery Miao", "hme": "Eastern Huishui Hmong", "hmg": "Southwestern Guiyang Hmong", "hmh": "Southwestern Huishui Hmong", "hmi": "Northern Huishui Hmong", "hmj": "Ge", "hml": "Luopohe Hmong", "hmm": "Central Mashan Hmong", "hmp": "Northern Mashan Hmong", "hmq": "Eastern Qiandong Miao", "hms": "Southern Qiandong Miao", "hmw": "Western Mashan Hmong", "hmy": "Southern Guiyang Hmong", "hmz": "Hmong Shua", "hnj": "Hmong Njua", "hrm": "Horned Miao", "huj": "Northern Guiyang Hmong", "mmr": "Western Xiangxi Miao", "muq": "Eastern Xiangxi Miao", "mww": "Hmong Daw", "sfm": "Small Flowery Miao"},
               "iku": {"ike": "Eastern Canadian Inuktitut", "ikt": "Inuinnaqtun"},
               "ipk": {"esi": "North Alaskan Inupiatun", "esk": "Northwest Alaska Inupiatun"},
               "jrb": {"ajt": "Judeo-Tunisian Arabic", "aju": "Judeo-Moroccan Arabic", "jye": "Judeo-Yemeni Arabic", "yhd": "Judeo-Iraqi Arabic", "yud": "Judeo-Tripolitanian Arabic"},
               "kau": {"kby": "Manga Kanuri", "knc": "Central Kanuri", "krt": "Tumari Kanuri"},
               "kln": {"enb": "Markweeta", "eyo": "Keiyo", "niq": "Nandi", "oki": "Okiek", "pko": "Pökoot", "sgc": "Kipsigis", "spy": "Sabaot", "tec": "Terik", "tuy": "Tugen"},
               "kok": {"gom": "Goan Konkani", "knn": "Konkani (individual language)"},
               "kom": {"koi": "Komi-Permyak", "kpv": "Komi-Zyrian"},
               "kon": {"kng": "Koongo", "kwy": "San Salvador Kongo", "ldi": "Laari"},
               "kpe": {"gkp": "Guinea Kpelle", "xpe": "Liberia Kpelle"},
               "kur": {"ckb": "Central Kurdish", "kmr": "Northern Kurdish", "sdh": "Southern Kurdish"},
               "lah": {"hnd": "Southern Hindko", "hno": "Northern Hindko", "jat": "Jakati", "phr": "Pahari-Potwari", "pmu": "Mirpur Panjabi", "pnb": "Western Panjabi", "skr": "Seraiki", "xhe": "Khetrani"},
               "lav": {"ltg": "Latgalian", "lvs": "Standard Latvian"},
               "luy": {"bxk": "Bukusu", "ida": "Idakho-Isukha-Tiriki", "lkb": "Kabras", "lko": "Khayo", "lks": "Kisa", "lri": "Marachi", "lrm": "Marama", "lsm": "Saamia", "lto": "Tsotso", "lts": "Tachoni", "lwg": "Wanga", "nle": "East Nyala", "nyd": "Nyore", "rag": "Logooli"},
               "man": {"emk": "Eastern Maninkakan", "mku": "Konyanka Maninka", "mlq": "Western Maninkakan", "mnk": "Mandinka", "msc": "Sankaran Maninka", "mwk": "Kita Maninkakan", "myq": "Forest Maninka  (Retired )"},
               "mlg": {"bhr": "Bara Malagasy", "bjq": "Southern Betsimisaraka Malagasy  (Retired )", "bmm": "Northern Betsimisaraka Malagasy", "bzc": "Southern Betsimisaraka Malagasy", "msh": "Masikoro Malagasy", "plt": "Plateau Malagasy", "skg": "Sakalava Malagasy", "tdx": "Tandroy-Mahafaly Malagasy", "tkg": "Tesaka Malagasy", "txy": "Tanosy Malagasy", "xmv": "Antankarana Malagasy", "xmw": "Tsimihety Malagasy"},
               "mon": {"khk": "Halh Mongolian", "mvf": "Peripheral Mongolian"},
               "msa": {"bjn": "Banjar", "btj": "Bacanese Malay", "bve": "Berau Malay", "bvu": "Bukit Malay", "coa": "Cocos Islands Malay", "dup": "Duano", "hji": "Haji", "ind": "Indonesian", "jak": "Jakun", "jax": "Jambi Malay", "kvb": "Kubu", "kvr": "Kerinci", "kxd": "Brunei", "lce": "Loncong", "lcf": "Lubu", "liw": "Col", "max": "North Moluccan Malay", "meo": "Kedah Malay", "mfa": "Pattani Malay", "mfb": "Bangka", "min": "Minangkabau", "mly": "Malay (individual language)  (Retired 2/18/2008)", "mqg": "Kota Bangun Kutai Malay", "msi": "Sabah Malay", "mui": "Musi", "orn": "Orang Kanaq", "ors": "Orang Seletar", "pel": "Pekal", "pse": "Central Malay", "tmw": "Temuan", "urk": "Urak Lawoi'", "vkk": "Kaur", "vkt": "Tenggarong Kutai Malay", "xmm": "Manado Malay", "zlm": "Malay (individual language)", "zmi": "Negeri Sembilan Malay", "zsm": "Standard Malay"},
               "mwr": {"dhd": "Dhundari", "mtr": "Mewari", "mve": "Marwari (Pakistan)", "rwr": "Marwari (India)", "swv": "Shekhawati", "wry": "Merwari"},
               "nep": {"dty": "Dotyali", "npi": "Nepali (individual language)"},
               "nor": {"nno": "Norwegian Nynorsk", "nob": "Norwegian Bokmål"},
               "oji": {"ciw": "Chippewa", "ojb": "Northwestern Ojibwa", "ojc": "Central Ojibwa", "ojg": "Eastern Ojibwa", "ojs": "Severn Ojibwa", "ojw": "Western Ojibwa", "otw": "Ottawa"},
               "ori": {"ory": "Oriya (individual language)", "spv": "Sambalpuri"},
               "orm": {"gax": "Borana-Arsi-Guji Oromo", "gaz": "West Central Oromo", "hae": "Eastern Oromo", "orc": "Orma"},
               "pus": {"pbt": "Southern Pashto", "pbu": "Northern Pashto", "pst": "Central Pashto"},
               "que": {"cqu": "Chilean Quechua", "qub": "Huallaga Huánuco Quechua", "qud": "Calderón Highland Quichua", "quf": "Lambayeque Quechua", "qug": "Chimborazo Highland Quichua", "quh": "South Bolivian Quechua", "quk": "Chachapoyas Quechua", "qul": "North Bolivian Quechua", "qup": "Southern Pastaza Quechua", "qur": "Yanahuanca Pasco Quechua", "qus": "Santiago del Estero Quichua", "quw": "Tena Lowland Quichua", "qux": "Yauyos Quechua", "quy": "Ayacucho Quechua", "quz": "Cusco Quechua", "qva": "Ambo-Pasco Quechua", "qvc": "Cajamarca Quechua", "qve": "Eastern Apurímac Quechua", "qvh": "Huamalíes-Dos de Mayo Huánuco Quechua", "qvi": "Imbabura Highland Quichua", "qvj": "Loja Highland Quichua", "qvl": "Cajatambo North Lima Quechua", "qvm": "Margos-Yarowilca-Lauricocha Quechua", "qvn": "North Junín Quechua", "qvo": "Napo Lowland Quechua", "qvp": "Pacaraos Quechua", "qvs": "San Martín Quechua", "qvw": "Huaylla Wanca Quechua", "qvz": "Northern Pastaza Quichua", "qwa": "Corongo Ancash Quechua", "qwc": "Classical Quechua", "qwh": "Huaylas Ancash Quechua", "qws": "Sihuas Ancash Quechua", "qxa": "Chiquián Ancash Quechua", "qxc": "Chincha Quechua", "qxh": "Panao Huánuco Quechua", "qxl": "Salasaca Highland Quichua", "qxn": "Northern Conchucos Ancash Quechua", "qxo": "Southern Conchucos Ancash Quechua", "qxp": "Puno Quechua", "qxr": "Cañar Highland Quichua", "qxt": "Santa Ana de Tusi Pasco Quechua", "qxu": "Arequipa-La Unión Quechua", "qxw": "Jauja Wanca Quechua"},
               "raj": {"bgq": "Bagri", "gda": "Gade Lohar", "gju": "Gujari", "hoj": "Hadothi", "mup": "Malvi", "wbr": "Wagdi"},
               "rom": {"rmc": "Carpathian Romani", "rmf": "Kalo Finnish Romani", "rml": "Baltic Romani", "rmn": "Balkan Romani", "rmo": "Sinte Romani", "rmw": "Welsh Romani", "rmy": "Vlax Romani"},
               "sqi": {"aae": "Arbëreshë Albanian", "aat": "Arvanitika Albanian", "aln": "Gheg Albanian", "als": "Tosk Albanian"},
               "srd": {"sdc": "Sassarese Sardinian", "sdn": "Gallurese Sardinian", "src": "Logudorese Sardinian", "sro": "Campidanese Sardinian"},
               "swa": {"swc": "Congo Swahili", "swh": "Swahili (individual language)"},
               "syr": {"aii": "Assyrian Neo-Aramaic", "cld": "Chaldean Neo-Aramaic"},
               "tmh": {"taq": "Tamasheq", "thv": "Tahaggart Tamahaq", "thz": "Tayart Tamajeq", "ttq": "Tawallammat Tamajaq"},
               "uzb": {"uzn": "Northern Uzbek", "uzs": "Southern Uzbek"},
               "yid": {"ydd": "Eastern Yiddish", "yih": "Western Yiddish"},
               "zap": {"zaa": "Sierra de Juárez Zapotec", "zab": "San Juan Guelavía Zapotec", "zac": "Ocotlán Zapotec", "zad": "Cajonos Zapotec", "zae": "Yareni Zapotec", "zaf": "Ayoquesco Zapotec", "zai": "Isthmus Zapotec", "zam": "Miahuatlán Zapotec", "zao": "Ozolotepec Zapotec", "zaq": "Aloápam Zapotec", "zar": "Rincón Zapotec", "zas": "Santo Domingo Albarradas Zapotec", "zat": "Tabaa Zapotec", "zav": "Yatzachi Zapotec", "zaw": "Mitla Zapotec", "zax": "Xadani Zapotec", "zca": "Coatecas Altas Zapotec", "zoo": "Asunción Mixtepec Zapotec", "zpa": "Lachiguiri Zapotec", "zpb": "Yautepec Zapotec", "zpc": "Choapan Zapotec", "zpd": "Southeastern Ixtlán Zapotec", "zpe": "Petapa Zapotec", "zpf": "San Pedro Quiatoni Zapotec", "zpg": "Guevea De Humboldt Zapotec", "zph": "Totomachapan Zapotec", "zpi": "Santa María Quiegolani Zapotec", "zpj": "Quiavicuzas Zapotec", "zpk": "Tlacolulita Zapotec", "zpl": "Lachixío Zapotec", "zpm": "Mixtepec Zapotec", "zpn": "Santa Inés Yatzechi Zapotec", "zpo": "Amatlán Zapotec", "zpp": "El Alto Zapotec", "zpq": "Zoogocho Zapotec", "zpr": "Santiago Xanica Zapotec", "zps": "Coatlán Zapotec", "zpt": "San Vicente Coatlán Zapotec", "zpu": "Yalálag Zapotec", "zpv": "Chichicapan Zapotec", "zpw": "Zaniza Zapotec", "zpx": "San Baltazar Loxicha Zapotec", "zpy": "Mazaltepec Zapotec", "zpz": "Texmelucan Zapotec", "zsr": "Southern Rincon Zapotec", "ztc": "Lachirioag Zapotec  (Retired 7/18/2007)", "zte": "Elotepec Zapotec", "ztg": "Xanaguía Zapotec", "ztl": "Lapaguía-Guivini Zapotec", "ztm": "San Agustín Mixtepec Zapotec", "ztn": "Santa Catarina Albarradas Zapotec", "ztp": "Loxicha Zapotec", "ztq": "Quioquitani-Quierí Zapotec", "zts": "Tilquiapan Zapotec", "ztt": "Tejalapan Zapotec", "ztu": "Güilá Zapotec", "ztx": "Zaachila Zapotec", "zty": "Yatee Zapotec"},
               "zha": {"ccx": "Northern Zhuang  (Retired 1/14/2008)", "ccy": "Southern Zhuang  (Retired 7/18/2007)", "zch": "Central Hongshuihe Zhuang", "zeh": "Eastern Hongshuihe Zhuang", "zgb": "Guibei Zhuang", "zgm": "Minz Zhuang", "zgn": "Guibian Zhuang", "zhd": "Dai Zhuang", "zhn": "Nong Zhuang", "zlj": "Liujiang Zhuang", "zln": "Lianshan Zhuang", "zlq": "Liuqian Zhuang", "zqe": "Qiubei Zhuang", "zyb": "Yongbei Zhuang", "zyg": "Yang Zhuang", "zyj": "Youjiang Zhuang", "zyn": "Yongnan Zhuang", "zzj": "Zuojiang Zhuang"},
               "zho": {"cdo": "Min Dong Chinese", "cjy": "Jinyu Chinese", "cmn": "Mandarin Chinese", "cpx": "Pu-Xian Chinese", "czh": "Huizhou Chinese", "czo": "Min Zhong Chinese", "gan": "Gan Chinese", "hak": "Hakka Chinese", "hsn": "Xiang Chinese", "lzh": "Literary Chinese", "mnp": "Min Bei Chinese", "nan": "Min Nan Chinese", "wuu": "Wu Chinese", "yue": "Yue Chinese"},
               "zza": {"diq": "Dimli (individual language)", "kiu": "Kirmanjki (individual language)"}}

def dead_to_dict(string):
  """
  Converts text copied from http://linguistlist.org/forms/langs/get-extinct.cfm
  to be initialised in a python dictionary format
  """
  lang_split = string.split('\n')
  lang_dict = []
  for x in lang_split:
    y = x.split('  ')
    lang_dict.append('"{}": "{}"'.format(y[1],y[0]))
  return '{' + ',\n        '.join(sorted(lang_dict)) + '}'

def macro_to_dict(string):
  """
  Converts text copied from http://www-01.sil.org/iso639-3/macrolanguages.asp
  to be initialised in a python dictionary format
  """
  macro_list = []
  member_list = []
  all_lines = string.split('\n')
  for line in all_lines:
    if line[0] == ' ':
      code, name = line[2:].strip().split('\t', 1)
      member_list[-1].append('"{}": "{}"'.format(code, name))
    else:
      macro_code, macro_name, code, name = line.split('\t')
      macro_list.append(macro_code)
      member_list.append(['"{}": "{}"'.format(code, name)])
  member_strings = ['"{}": {{{}}}'.format(macro_list[i], ', '.join(member_list[i])) for i in range(len(member_list))]
  return "{" + ",\n               ".join(member_strings) + "}"

def retired_to_tuples(string):
  """
  Converts .tab file from http://www-01.sil.org/iso639-3/iso-639-3_Retirements.tab
  (without first line) to be intitialised as a list of tuples
  """
  lines = ['("' + '", "'.join(x.split('\t')) + '")' for x in string.split('\n')]
  return '[' + ',\n					 '.join(lines) + ']'

if __name__ == '__main__':
  print(retired_convert)