# -*- coding: utf-8 -*-

constructed = {"ido":"Ido",
               "tlh":"Klingon",
               "tzl":"Talossan",
               "jbo":"Lojban",
               "ina":"Interlingua",
               "epo":"Esperanto",
               # Additional constructed languages from http://linguistlist.org/forms/langs/GetListOfConstructedLgs.cfm
               "bzt": "Brithenig",
               "dws": "Dutton",
               "igs": "Interglossa",
               "ldn": "Láadan",
               "nov": "Novial",
               "occ": "Occidental",
               "qya": "Quenya",
               "rmv": "Romanova",
               "sjn": "Sindarin",
               "vol": "Volapük"}

dead = {"aaq": "Abnaki, Eastern",
        "abj": "Aka-Bea",
        "aci": "Aka-Cari",
        "ack": "Aka-Kora",
        "acl": "Akar-Bale",
        "acs": "Acroá",
        "aes": "Alsea",
        "aga": "Aguano",
        "aho": "Ahom",
        "ait": "Arikem",
        "ajw": "Ajawa",
        "akj": "Aka-Jeru",
        "akk": "Akkadian",
        "akm": "Aka-Bo",
        "akx": "Aka-Kede",
        "aky": "Aka-Kol",
        "ana": "Andaqui",
        "anb": "Andoa",
        "ang": "English, Old",
        "ans": "Anserma",
        "aoh": "Arma",
        "aqp": "Atakapa",
        "arc": "Aramaic, Official",
        "aru": "Aruá",
        "ash": "Abishira",
        "atc": "Atsahuaca",
        "auo": "Auyokawa",
        "ave": "Avestan",
        "avs": "Aushiri",
        "awk": "Awabakal",
        "axb": "Abipon",
        "axg": "Arára, Mato Grosso",
        "axm": "Armenian, Middle",
        "ayy": "Ayta, Tayabas",
        "bae": "Baré",
        "bjb": "Banggarla",
        "bjf": "Neo-Aramaic, Barzani Jewish",
        "bjy": "Bayali",
        "bll": "Biloxi",
        "bmn": "Bina",
        "boi": "Barbareño",
        "bow": "Rema",
        "bpb": "Barbacoas",
        "bqf": "Baga Kaloum",
        "brk": "Birked",
        "bsl": "Basa-Gumna",
        "bsv": "Baga Sobané",
        "bte": "Gamo-Ningi",
        "bue": "Beothuk",
        "bvv": "Baniva",
        "bxi": "Pirlatapa",
        "byg": "Baygo",
        "byq": "Basay",
        "byt": "Berti",
        "bzr": "Biri",
        "caj": "Chané",
        "caz": "Canichana",
        "cbe": "Chipiajes",
        "cbh": "Cagua",
        "cca": "Cauca",
        "ccr": "Cacaopera",
        "chb": "Chibcha",
        "chc": "Catawba",
        "chg": "Chagatai",
        "chs": "Chumash",
        "cht": "Cholón",
        "chu": "Slavonic, Old",
        "cid": "Chimariko",
        "cjr": "Chorotega",
        "cmg": "Mongolian, Classical",
        "cmk": "Chimakum",
        "cmm": "Michigamea",
        "cms": "Messapic",
        "cnx": "Cornish, Middle",
        "cob": "Chicomuceltec",
        "coj": "Cochimi",
        "cop": "Coptic",
        "coq": "Coquille",
        "coy": "Coyaima",
        "cpg": "Greek, Cappadocian",
        "crb": "Carib, Island",
        "crf": "Caramanta",
        "crr": "Algonquian, Carolina",
        "crz": "Cruzeño",
        "csi": "Miwok, Coast",
        "css": "Ohlone, Southern",
        "cst": "Ohlone, Northern",
        "ctm": "Chitimacha",
        "cum": "Cumeral",
        "cuo": "Cumanagoto",
        "cyb": "Cayubaba",
        "czk": "Knaanic",
        "dcr": "Negerhollands",
        "dep": "Delaware, Pidgin",
        "dgn": "Dagoman",
        "dhu": "Dhurga",
        "dif": "Dieri",
        "dlm": "Dalmatian",
        "drq": "Dura",
        "drr": "Dororo",
        "dum": "Dutch, Middle",
        "duy": "Agta, Dicamay",
        "duz": "Duli",
        "ecr": "Eteocretan",
        "ecy": "Eteocypriot",
        "egy": "Egyptian",
        "elx": "Elamite",
        "emm": "Mamulique",
        "emo": "Emok",
        "emy": "Mayan, Epigraphic",
        "enm": "English, Middle",
        "esm": "Esuma",
        "esq": "Esselen",
        "etc": "Etchemin",
        "ett": "Etruscan",
        "fos": "Siraya",
        "frk": "Frankish",
        "frm": "French, Middle",
        "fro": "French, Old",
        "gce": "Galice",
        "gez": "Geez",
        "gft": "Gafat",
        "ggk": "Kungarakany",
        "ggr": "Aghu Tharnggalu",
        "ghc": "Gaelic, Hiberno-Scottish",
        "gho": "Ghomara",
        "gli": "Guliguli",
        "glv": "Manx",
        "gly": "Gule",
        "gmh": "German, Middle High",
        "gml": "German, Middle Low",
        "gmy": "Greek, Mycenaean",
        "gnc": "Guanche",
        "gnl": "Gangulu",
        "gnr": "Gureng Gureng",
        "goh": "German, Old High",
        "got": "Gothic",
        "gqn": "Guana",
        "grc": "Greek, Ancient",
        "guv": "Gey",
        "gvy": "Guyani",
        "hbo": "Hebrew, Ancient",
        "hib": "Hibito",
        "hit": "Hittite",
        "hlu": "Luwian, Hieroglyphic",
        "hmk": "Maek",
        "hom": "Homa",
        "hor": "Horo",
        "htx": "Hittite, Middle",
        "iff": "Ifo",
        "iml": "Miluk",
        "ims": "Marsian",
        "imy": "Milyan",
        "inm": "Minaean",
        "inz": "Ineseño",
        "iow": "Iowa-Oto",
        "ite": "Itene",
        "jgb": "Ngbee",
        "jor": "Jorá",
        "jpa": "Aramaic, Jewish Palestinian",
        "juc": "Jurchen",
        "kae": "Ketangalan",
        "kaw": "Kawi",
        "kba": "Kalarko",
        "kbf": "Kakauhua",
        "kda": "Worimi",
        "kgg": "Kusunda",
        "kgm": "Karipúna",
        "kii": "Kitsai",
        "koc": "Kpati",
        "kof": "Kubi",
        "kox": "Coxima",
        "kpn": "Kepkiriwát",
        "kqu": "Seroa",
        "krb": "Karkin",
        "ktg": "Kalkutung",
        "ktk": "Kaniet",
        "ktq": "Katabaga",
        "kuz": "Kunza",
        "kwz": "Kwadi",
        "kxo": "Kanoé",
        "kzk": "Kazukuru",
        "kzw": "Karirí-Xocó",
        "lab": "Linear A",
        "lat": "Latin",
        "laz": "Aribwatsa",
        "lhs": "Mlahsö",
        "llf": "Hermit",
        "lmz": "Lumbee",
        "lng": "Langobardic",
        "lnj": "Leningitij",
        "lre": "Laurentian",
        "ltc": "Chinese, Late Middle",
        "mbe": "Molale",
        "mcl": "Macaguaje",
        "mfw": "Mulaha",
        "mga": "Irish, Middle",
        "mia": "Miami",
        "mje": "Muskum",
        "mjy": "Mahican",
        "mkq": "Miwok, Bay",
        "mnt": "Maykulan",
        "mod": "Mobilian",
        "mof": "Mohegan-Montauk-Narragansett",
        "mom": "Mangue",
        "msp": "Maritsauá",
        "mtm": "Mator",
        "mtn": "Matagalpa",
        "mvb": "Mattole",
        "mvl": "Mbara",
        "mwu": "Mittu",
        "mxi": "Mozarabic",
        "mys": "Mesmes",
        "myz": "Mandaic, Classical",
        "nay": "Narrinyeri",
        "nci": "Nahuatl, Classical",
        "ncz": "Natchez",
        "ndf": "Nadruvian",
        "nei": "Hittite, Neo-",
        "ngv": "Nagumi",
        "nhc": "Nahuatl, Tabasco",
        "nid": "Ngandi",
        "nkp": "Niuatoputapu",
        "nnt": "Nanticoke",
        "nok": "Nooksack",
        "nom": "Nocamán",
        "non": "Norse, Old",
        "nrc": "Noric",
        "nrn": "Norn",
        "nrp": "Picene, North",
        "nrt": "Kalapuya, Northern",
        "nts": "Natagaimas",
        "ntw": "Nottoway",
        "nuc": "Nukuini",
        "nwa": "Nawathinehena",
        "nwx": "Newar, Middle",
        "nwy": "Nottoway-Meherrin",
        "nxm": "Numidian",
        "nyp": "Nyang'i",
        "nyx": "Nganyaywana",
        "oar": "Aramaic, Old",
        "oav": "Avar, Old",
        "obi": "Obispeño",
        "obm": "Moabite",
        "obr": "Burmese, Old",
        "obt": "Breton, Old",
        "och": "Chinese, Old",
        "oco": "Cornish, Old",
        "odt": "Dutch, Old",
        "ofo": "Ofo",
        "ofs": "Frisian, Old",
        "oge": "Georgian, Old",
        "oht": "Hittite, Old",
        "ohu": "Hungarian, Old",
        "ojp": "Japanese, Old",
        "okj": "Oko-Juwoi",
        "okm": "Korean, Middle",
        "oko": "Korean, Old",
        "omc": "Mochica",
        "ome": "Omejes",
        "omk": "Omok",
        "omn": "Minoan",
        "omp": "Manipuri, Old",
        "omr": "Marathi, Old",
        "omu": "Omurano",
        "omx": "Mon, Old",
        "onw": "Nubian, Old",
        "oos": "Ossetic, Old",
        "opy": "Ofayé",
        "orv": "Russian, Old",
        "osc": "Oscan",
        "osp": "Spanish, Old",
        "osx": "Saxon, Old",
        "otb": "Tibetan, Old",
        "oti": "Oti",
        "otk": "Turkish, Old",
        "otu": "Otuke",
        "oty": "Tamil, Old",
        "oui": "Uighur, Old",
        "oum": "Ouma",
        "owl": "Welsh, Old",
        "paf": "Paranawát",
        "pal": "Pahlavi",
        "pax": "Pankararé",
        "paz": "Pankararú",
        "peb": "Pomo, Eastern",
        "pej": "Pomo, Northern",
        "peo": "Persian, Old",
        "pgn": "Paelignian",
        "phn": "Phoenician",
        "pie": "Piro",
        "pij": "Pijao",
        "pim": "Powhatan",
        "pka": "Prākrit, Ardhamāgadhī",
        "pkc": "Paekche",
        "pli": "Pali",
        "plq": "Palaic",
        "pmc": "Palumata",
        "pmh": "Prākrit, Māhārāṣṭri",
        "pmk": "Pamlico",
        "pml": "Lingua Franca",
        "pmz": "Pame, Southern",
        "pno": "Panobo",
        "pod": "Ponares",
        "pog": "Potiguára",
        "pox": "Polabian",
        "ppu": "Papora",
        "prg": "Prussian",
        "pro": "Provençal, Old",
        "prr": "Puri",
        "psu": "Prākrit, Sauraseni",
        "psy": "Piscataway",
        "pth": "Pataxó Hã-Ha-Hãe",
        "ptw": "Pentlatch",
        "puq": "Puquina",
        "puy": "Purisimeño",
        "pyx": "Pyu",
        "qey": "Sam'alian",
        "qgg": "Ammonite",
        "qgk": "Middle Greek",
        "qgu": "Wulguru",
        "qkn": "Old Kannada",
        "qok": "Old Khmer",
        "qpp": "Paisaci Prakrit",
        "qwc": "Quechua, Classical",
        "qwm": "Kuman",
        "qwt": "Kwalhioqua-Tlatskanai",
        "rem": "Remo",
        "rna": "Runa",
        "sam": "Aramaic, Samaritan",
        "sar": "Saraveca",
        "sbv": "Sabine",
        "scx": "Sicel",
        "sds": "Sened",
        "sdt": "Shuadit",
        "sga": "Irish, Old",
        "sgm": "Singa",
        "sis": "Siuslaw",
        "sjk": "Sami, Kemi",
        "sjs": "Senhaja De Srair",
        "skw": "Creole Dutch, Skepi",
        "sln": "Salinan",
        "smp": "Samaritan",
        "snh": "Shinabo",
        "sni": "Sensi",
        "sog": "Sogdian",
        "spx": "Picene, South",
        "sqn": "Susquehannock",
        "sut": "Subtiaba",
        "sux": "Sumerian",
        "svx": "Skalvian",
        "sxc": "Sicanian",
        "sxk": "Kalapuya, Southern",
        "sxl": "Selian",
        "sxo": "Sorothaptic",
        "syc": "Syriac, Classical",
        "szd": "Seru",
        "tas": "Tay Boi",
        "tbb": "Tapeba",
        "tbh": "Thurawal",
        "tbu": "Tubar",
        "teb": "Tetete",
        "ten": "Tama",
        "tep": "Tepecano",
        "tgv": "Tingui-Boto",
        "tgy": "Togoyo",
        "til": "Tillamook",
        "tjm": "Timucua",
        "tjn": "Tonjon",
        "tju": "Tjurruru",
        "tka": "Truká",
        "tkf": "Tukumanféd",
        "tkm": "Takelma",
        "tmg": "Ternateño",
        "tmr": "Aramaic, Jewish Babylonian",
        "tmz": "Tamanaku",
        "tnq": "Taino",
        "tnx": "Tanema",
        "toe": "Tomedes",
        "tpk": "Tupinikin",
        "tpn": "Tupinambá",
        "tpw": "Tupí",
        "tqr": "Torona",
        "tqw": "Tonkawa",
        "try": "Turung",
        "tta": "Tutelo",
        "ttk": "Totoro",
        "tud": "Tuxá",
        "tun": "Tunica",
        "tux": "Tuxináwa",
        "tvy": "Pidgin, Timor",
        "twa": "Twana",
        "twc": "Teshenawa",
        "twt": "Turiwára",
        "txb": "Tokharian B",
        "txc": "Tsetsaut",
        "txg": "Tangut",
        "txh": "Thracian",
        "txr": "Tartessian",
        "uam": "Uamué",
        "uby": "Ubykh",
        "uga": "Ugaritic",
        "umc": "Marrucinian",
        "umo": "Umotína",
        "unm": "Unami",
        "uru": "Urumi",
        "urv": "Uruava",
        "uun": "Kulon-Pazeh",
        "veo": "Ventureño",
        "vka": "Kariyarra",
        "vkm": "Kamakan",
        "vml": "Malgana",
        "vms": "Moksela",
        "vmv": "Maidu, Valley",
        "vnk": "Vano",
        "waf": "Wakoná",
        "wam": "Wampanoag",
        "wir": "Wiraféd",
        "wiy": "Wiyot",
        "wka": "Kw'adza",
        "wlk": "Wailaki",
        "wlm": "Welsh, Middle",
        "wlu": "Wuliwuli",
        "wma": "Mawa",
        "wmn": "Waamwang",
        "wnd": "Wandarang",
        "woy": "Weyto",
        "wri": "Wariyangga",
        "wrw": "Gugu Warra",
        "wsu": "Wasu",
        "wur": "Wurrugu",
        "wya": "Wyandot",
        "xaa": "Arabic, Andalusian",
        "xad": "Adai",
        "xae": "Aequian",
        "xag": "Aghwan",
        "xai": "Kaimbé",
        "xam": "/Xam",
        "xap": "Apalachee",
        "xaq": "Aquitanian",
        "xar": "Karami",
        "xas": "Kamas",
        "xba": "Kamba",
        "xbc": "Bactrian",
        "xbm": "Breton, Middle",
        "xbo": "Bolgarian",
        "xbw": "Kambiwá",
        "xcb": "Cumbric",
        "xcc": "Camunic",
        "xce": "Celtiberian",
        "xcg": "Gaulish, Cisalpine",
        "xch": "Chimakum",
        "xcl": "Armenian, Classical",
        "xcm": "Comecrudo",
        "xcn": "Cotoname",
        "xco": "Chorasmian",
        "xcr": "Carian",
        "xct": "Tibetan, Classical",
        "xcu": "Curonian",
        "xcv": "Chuvantsy",
        "xcw": "Coahuilteco",
        "xcy": "Cayuse",
        "xdc": "Dacian",
        "xdm": "Edomite",
        "xdr": "Deir Alla",
        "xeb": "Eblan",
        "xeg": "//Xegwi",
        "xep": "Epi-Olmec",
        "xfa": "Faliscan",
        "xga": "Galatian",
        "xgf": "Gabrielino-Fernandeño",
        "xgl": "Galindan",
        "xgr": "Garza",
        "xha": "Harami",
        "xhc": "Hunnic",
        "xhd": "Hadrami",
        "xhr": "Hernican",
        "xht": "Hattic",
        "xhu": "Hurrian",
        "xib": "Iberian",
        "xil": "Illyrian",
        "xin": "Xinca",
        "xiv": "Indus Valley Language",
        "xkr": "Xakriabá",
        "xlb": "Loup B",
        "xlc": "Lycian",
        "xld": "Lydian",
        "xle": "Lemnian",
        "xlg": "Ligurian",
        "xli": "Liburnian",
        "xln": "Alanic",
        "xlo": "Loup A",
        "xlp": "Lepontic",
        "xls": "Lusitanian",
        "xlu": "Luwian, Cuneiform",
        "xly": "Elymian",
        "xme": "Median",
        "xmk": "Macedonian, Ancient",
        "xmn": "Persian, Manichaean Middle",
        "xmr": "Meroitic",
        "xna": "North Arabian, Ancient",
        "xng": "Mongolian, Middle",
        "xno": "Anglo-Norman",
        "xoo": "Xukurú",
        "xpc": "Pecheneg",
        "xpg": "Phrygian",
        "xpi": "Pictish",
        "xpm": "Pumpokol",
        "xpn": "Kapinawá",
        "xpo": "Pochutec",
        "xpp": "Puyo-Paekche",
        "xpr": "Parthian",
        "xps": "Pisidian",
        "xpu": "Punic",
        "xpy": "Puyo",
        "xqa": "Karakhanid",
        "xqt": "Qatabanian",
        "xrm": "Armazic",
        "xrn": "Arin",
        "xrr": "Raetic",
        "xrt": "Aranama-Tamique",
        "xsa": "Sabaean",
        "xsc": "Scythian",
        "xsd": "Sidetic",
        "xsk": "Sakan",
        "xso": "Solano",
        "xss": "Assan",
        "xsv": "Sudovian",
        "xtg": "Gaulish, Transalpine",
        "xto": "Tokharian A",
        "xtq": "Tumshuqese",
        "xtr": "Tripuri, Early",
        "xtz": "Tasmanian",
        "xum": "Umbrian",
        "xup": "Umpqua, Upper",
        "xur": "Urartian",
        "xve": "Venetic",
        "xvn": "Vandalic",
        "xvo": "Volscian",
        "xvs": "Vestinian",
        "xwc": "Woccon",
        "xwo": "Oirat, Written",
        "xzh": "Zhang-Zhung",
        "xzm": "Zemgalian",
        "xzp": "Zapotec, Ancient",
        "ybn": "Yabaâna",
        "yei": "Yeni",
        "ylr": "Yalarnnga",
        "yme": "Yameo",
        "yms": "Mysian",
        "ymt": "Mator-Taygi-Karagas",
        "ynn": "Yana",
        "ynu": "Yahuna",
        "yob": "Yoba",
        "ysc": "Yassic",
        "ysr": "Yupik, Sirenik",
        "yub": "Yugambal",
        "yug": "Yug",
        "yvt": "Yavitero",
        "zkb": "Koibal",
        "zkg": "Koguryo",
        "zkh": "Khorezmian",
        "zkk": "Karankawa",
        "zko": "Kott",
        "zkt": "Kitan",
        "zku": "Kaurna",
        "zkv": "Krevinian",
        "zkz": "Khazar",
        "znk": "Manangkari",
        "zra": "Kara",
        "zrp": "Zarphatic",
        "zsk": "Kaskean"}

macro_split = {"aka": {"fat": "Fanti", "twi": "Twi"},
               "ara": {"aao": "Algerian Saharan Arabic", "abh": "Tajiki Arabic", "abv": "Baharna Arabic", "acm": "Mesopotamian Arabic", "acq": "Ta'izzi-Adeni Arabic", "acw": "Hijazi Arabic", "acx": "Omani Arabic", "acy": "Cypriot Arabic", "adf": "Dhofari Arabic", "aeb": "Tunisian Arabic", "aec": "Saidi Arabic", "afb": "Gulf Arabic", "ajp": "South Levantine Arabic", "apc": "North Levantine Arabic", "apd": "Sudanese Arabic", "arb": "Standard Arabic", "arq": "Algerian Arabic", "ars": "Najdi Arabic", "ary": "Moroccan Arabic", "arz": "Egyptian Arabic", "auz": "Uzbeki Arabic", "avl": "Eastern Egyptian Bedawi Arabic", "ayh": "Hadrami Arabic", "ayl": "Libyan Arabic", "ayn": "Sanaani Arabic", "ayp": "North Mesopotamian Arabic", "bbz": "Babalia Creole Arabic", "pga": "Sudanese Creole Arabic", "shu": "Chadian Arabic", "ssh": "Shihhi Arabic"},
               "aym": {"ayc": "Southern Aymara", "ayr": "Central Aymara"},
               "aze": {"azb": "South Azerbaijani", "azj": "North Azerbaijani"},
               "bal": {"bcc": "Southern Balochi", "bgn": "Western Balochi", "bgp": "Eastern Balochi"},
               "bik": {"bcl": "Central Bikol", "bhk": "Albay Bicolano  (Retired 1/15/2010)", "bln": "Southern Catanduanes Bikol", "bto": "Rinconada Bikol", "cts": "Northern Catanduanes Bikol", "fbl": "West Albay Bikol", "lbl": "Libon Bikol", "rbl": "Miraya Bikol", "ubl": "Buhi'non Bikol"},
               "bnc": {"ebk": "Eastern Bontok", "lbk": "Central Bontok", "obk": "Southern Bontok", "rbk": "Northern Bontok", "vbk": "Southwestern Bontok"},
               "bua": {"bxm": "Mongolia Buriat", "bxr": "Russia Buriat", "bxu": "China Buriat"},
               "chm": {"mhr": "Eastern Mari", "mrj": "Western Mari"},
               "cre": {"crj": "Southern East Cree", "crk": "Plains Cree", "crl": "Northern East Cree", "crm": "Moose Cree", "csw": "Swampy Cree", "cwd": "Woods Cree"},
               "del": {"umu": "Munsee", "unm": "Unami"},
               "den": {"scs": "North Slavey", "xsl": "South Slavey"},
               "din": {"dib": "South Central Dinka", "dik": "Southwestern Dinka", "dip": "Northeastern Dinka", "diw": "Northwestern Dinka", "dks": "Southeastern Dinka"},
               "doi": {"dgo": "Dogri (individual language)", "xnr": "Kangri"},
               "est": {"ekk": "Standard Estonian", "vro": "Võro"},
               "fas": {"pes": "Iranian Persian", "prs": "Dari"},
               "ful": {"ffm": "Maasina Fulfulde", "fub": "Adamawa Fulfulde", "fuc": "Pulaar", "fue": "Borgu Fulfulde", "fuf": "Pular", "fuh": "Western Niger Fulfulde", "fui": "Bagirmi Fulfulde", "fuq": "Central-Eastern Niger Fulfulde", "fuv": "Nigerian Fulfulde"},
               "gba": {"bdt": "Bokoto", "gbp": "Gbaya-Bossangoa", "gbq": "Gbaya-Bozoum", "gmm": "Gbaya-Mbodomo", "gso": "Southwest Gbaya", "gya": "Northwest Gbaya", "mdo": "Southwest Gbaya  (Retired 1/14/2008)"},
               "gon": {"ggo": "Southern Gondi", "gno": "Northern Gondi"},
               "grb": {"gbo": "Northern Grebo", "gec": "Gboloo Grebo", "grj": "Southern Grebo", "grv": "Central Grebo", "gry": "Barclayville Grebo"},
               "grn": {"gnw": "Western Bolivian Guaraní", "gug": "Paraguayan Guaraní", "gui": "Eastern Bolivian Guaraní", "gun": "Mbyá Guaraní", "nhd": "Chiripá"},
               "hai": {"hax": "Southern Haida", "hdn": "Northern Haida"},
               "hbs": {"bos": "Bosnian", "hrv": "Croatian", "srp": "Serbian"},
               "hmn": {"blu": "Hmong Njua  (Retired 1/14/2008)", "cqd": "Chuanqiandian Cluster Miao", "hea": "Northern Qiandong Miao", "hma": "Southern Mashan Hmong", "hmc": "Central Huishui Hmong", "hmd": "Large Flowery Miao", "hme": "Eastern Huishui Hmong", "hmg": "Southwestern Guiyang Hmong", "hmh": "Southwestern Huishui Hmong", "hmi": "Northern Huishui Hmong", "hmj": "Ge", "hml": "Luopohe Hmong", "hmm": "Central Mashan Hmong", "hmp": "Northern Mashan Hmong", "hmq": "Eastern Qiandong Miao", "hms": "Southern Qiandong Miao", "hmw": "Western Mashan Hmong", "hmy": "Southern Guiyang Hmong", "hmz": "Hmong Shua", "hnj": "Hmong Njua", "hrm": "Horned Miao", "huj": "Northern Guiyang Hmong", "mmr": "Western Xiangxi Miao", "muq": "Eastern Xiangxi Miao", "mww": "Hmong Daw", "sfm": "Small Flowery Miao"},
               "iku": {"ike": "Eastern Canadian Inuktitut", "ikt": "Inuinnaqtun"},
               "ipk": {"esi": "North Alaskan Inupiatun", "esk": "Northwest Alaska Inupiatun"},
               "jrb": {"ajt": "Judeo-Tunisian Arabic", "aju": "Judeo-Moroccan Arabic", "jye": "Judeo-Yemeni Arabic", "yhd": "Judeo-Iraqi Arabic", "yud": "Judeo-Tripolitanian Arabic"},
               "kau": {"kby": "Manga Kanuri", "knc": "Central Kanuri", "krt": "Tumari Kanuri"},
               "kln": {"enb": "Markweeta", "eyo": "Keiyo", "niq": "Nandi", "oki": "Okiek", "pko": "Pökoot", "sgc": "Kipsigis", "spy": "Sabaot", "tec": "Terik", "tuy": "Tugen"},
               "kok": {"gom": "Goan Konkani", "knn": "Konkani (individual language)"},
               "kom": {"koi": "Komi-Permyak", "kpv": "Komi-Zyrian"},
               "kon": {"kng": "Koongo", "kwy": "San Salvador Kongo", "ldi": "Laari"},
               "kpe": {"gkp": "Guinea Kpelle", "xpe": "Liberia Kpelle"},
               "kur": {"ckb": "Central Kurdish", "kmr": "Northern Kurdish", "sdh": "Southern Kurdish"},
               "lah": {"hnd": "Southern Hindko", "hno": "Northern Hindko", "jat": "Jakati", "phr": "Pahari-Potwari", "pmu": "Mirpur Panjabi", "pnb": "Western Panjabi", "skr": "Seraiki", "xhe": "Khetrani"},
               "lav": {"ltg": "Latgalian", "lvs": "Standard Latvian"},
               "luy": {"bxk": "Bukusu", "ida": "Idakho-Isukha-Tiriki", "lkb": "Kabras", "lko": "Khayo", "lks": "Kisa", "lri": "Marachi", "lrm": "Marama", "lsm": "Saamia", "lto": "Tsotso", "lts": "Tachoni", "lwg": "Wanga", "nle": "East Nyala", "nyd": "Nyore", "rag": "Logooli"},
               "man": {"emk": "Eastern Maninkakan", "mku": "Konyanka Maninka", "mlq": "Western Maninkakan", "mnk": "Mandinka", "msc": "Sankaran Maninka", "mwk": "Kita Maninkakan", "myq": "Forest Maninka  (Retired )"},
               "mlg": {"bhr": "Bara Malagasy", "bjq": "Southern Betsimisaraka Malagasy  (Retired )", "bmm": "Northern Betsimisaraka Malagasy", "bzc": "Southern Betsimisaraka Malagasy", "msh": "Masikoro Malagasy", "plt": "Plateau Malagasy", "skg": "Sakalava Malagasy", "tdx": "Tandroy-Mahafaly Malagasy", "tkg": "Tesaka Malagasy", "txy": "Tanosy Malagasy", "xmv": "Antankarana Malagasy", "xmw": "Tsimihety Malagasy"},
               "mon": {"khk": "Halh Mongolian", "mvf": "Peripheral Mongolian"},
               "msa": {"bjn": "Banjar", "btj": "Bacanese Malay", "bve": "Berau Malay", "bvu": "Bukit Malay", "coa": "Cocos Islands Malay", "dup": "Duano", "hji": "Haji", "ind": "Indonesian", "jak": "Jakun", "jax": "Jambi Malay", "kvb": "Kubu", "kvr": "Kerinci", "kxd": "Brunei", "lce": "Loncong", "lcf": "Lubu", "liw": "Col", "max": "North Moluccan Malay", "meo": "Kedah Malay", "mfa": "Pattani Malay", "mfb": "Bangka", "min": "Minangkabau", "mly": "Malay (individual language)  (Retired 2/18/2008)", "mqg": "Kota Bangun Kutai Malay", "msi": "Sabah Malay", "mui": "Musi", "orn": "Orang Kanaq", "ors": "Orang Seletar", "pel": "Pekal", "pse": "Central Malay", "tmw": "Temuan", "urk": "Urak Lawoi'", "vkk": "Kaur", "vkt": "Tenggarong Kutai Malay", "xmm": "Manado Malay", "zlm": "Malay (individual language)", "zmi": "Negeri Sembilan Malay", "zsm": "Standard Malay"},
               "mwr": {"dhd": "Dhundari", "mtr": "Mewari", "mve": "Marwari (Pakistan)", "rwr": "Marwari (India)", "swv": "Shekhawati", "wry": "Merwari"},
               "nep": {"dty": "Dotyali", "npi": "Nepali (individual language)"},
               "nor": {"nno": "Norwegian Nynorsk", "nob": "Norwegian Bokmål"},
               "oji": {"ciw": "Chippewa", "ojb": "Northwestern Ojibwa", "ojc": "Central Ojibwa", "ojg": "Eastern Ojibwa", "ojs": "Severn Ojibwa", "ojw": "Western Ojibwa", "otw": "Ottawa"},
               "ori": {"ory": "Oriya (individual language)", "spv": "Sambalpuri"},
               "orm": {"gax": "Borana-Arsi-Guji Oromo", "gaz": "West Central Oromo", "hae": "Eastern Oromo", "orc": "Orma"},
               "pus": {"pbt": "Southern Pashto", "pbu": "Northern Pashto", "pst": "Central Pashto"},
               "que": {"cqu": "Chilean Quechua", "qub": "Huallaga Huánuco Quechua", "qud": "Calderón Highland Quichua", "quf": "Lambayeque Quechua", "qug": "Chimborazo Highland Quichua", "quh": "South Bolivian Quechua", "quk": "Chachapoyas Quechua", "qul": "North Bolivian Quechua", "qup": "Southern Pastaza Quechua", "qur": "Yanahuanca Pasco Quechua", "qus": "Santiago del Estero Quichua", "quw": "Tena Lowland Quichua", "qux": "Yauyos Quechua", "quy": "Ayacucho Quechua", "quz": "Cusco Quechua", "qva": "Ambo-Pasco Quechua", "qvc": "Cajamarca Quechua", "qve": "Eastern Apurímac Quechua", "qvh": "Huamalíes-Dos de Mayo Huánuco Quechua", "qvi": "Imbabura Highland Quichua", "qvj": "Loja Highland Quichua", "qvl": "Cajatambo North Lima Quechua", "qvm": "Margos-Yarowilca-Lauricocha Quechua", "qvn": "North Junín Quechua", "qvo": "Napo Lowland Quechua", "qvp": "Pacaraos Quechua", "qvs": "San Martín Quechua", "qvw": "Huaylla Wanca Quechua", "qvz": "Northern Pastaza Quichua", "qwa": "Corongo Ancash Quechua", "qwc": "Classical Quechua", "qwh": "Huaylas Ancash Quechua", "qws": "Sihuas Ancash Quechua", "qxa": "Chiquián Ancash Quechua", "qxc": "Chincha Quechua", "qxh": "Panao Huánuco Quechua", "qxl": "Salasaca Highland Quichua", "qxn": "Northern Conchucos Ancash Quechua", "qxo": "Southern Conchucos Ancash Quechua", "qxp": "Puno Quechua", "qxr": "Cañar Highland Quichua", "qxt": "Santa Ana de Tusi Pasco Quechua", "qxu": "Arequipa-La Unión Quechua", "qxw": "Jauja Wanca Quechua"},
               "raj": {"bgq": "Bagri", "gda": "Gade Lohar", "gju": "Gujari", "hoj": "Hadothi", "mup": "Malvi", "wbr": "Wagdi"},
               "rom": {"rmc": "Carpathian Romani", "rmf": "Kalo Finnish Romani", "rml": "Baltic Romani", "rmn": "Balkan Romani", "rmo": "Sinte Romani", "rmw": "Welsh Romani", "rmy": "Vlax Romani"},
               "sqi": {"aae": "Arbëreshë Albanian", "aat": "Arvanitika Albanian", "aln": "Gheg Albanian", "als": "Tosk Albanian"},
               "srd": {"sdc": "Sassarese Sardinian", "sdn": "Gallurese Sardinian", "src": "Logudorese Sardinian", "sro": "Campidanese Sardinian"},
               "swa": {"swc": "Congo Swahili", "swh": "Swahili (individual language)"},
               "syr": {"aii": "Assyrian Neo-Aramaic", "cld": "Chaldean Neo-Aramaic"},
               "tmh": {"taq": "Tamasheq", "thv": "Tahaggart Tamahaq", "thz": "Tayart Tamajeq", "ttq": "Tawallammat Tamajaq"},
               "uzb": {"uzn": "Northern Uzbek", "uzs": "Southern Uzbek"},
               "yid": {"ydd": "Eastern Yiddish", "yih": "Western Yiddish"},
               "zap": {"zaa": "Sierra de Juárez Zapotec", "zab": "San Juan Guelavía Zapotec", "zac": "Ocotlán Zapotec", "zad": "Cajonos Zapotec", "zae": "Yareni Zapotec", "zaf": "Ayoquesco Zapotec", "zai": "Isthmus Zapotec", "zam": "Miahuatlán Zapotec", "zao": "Ozolotepec Zapotec", "zaq": "Aloápam Zapotec", "zar": "Rincón Zapotec", "zas": "Santo Domingo Albarradas Zapotec", "zat": "Tabaa Zapotec", "zav": "Yatzachi Zapotec", "zaw": "Mitla Zapotec", "zax": "Xadani Zapotec", "zca": "Coatecas Altas Zapotec", "zoo": "Asunción Mixtepec Zapotec", "zpa": "Lachiguiri Zapotec", "zpb": "Yautepec Zapotec", "zpc": "Choapan Zapotec", "zpd": "Southeastern Ixtlán Zapotec", "zpe": "Petapa Zapotec", "zpf": "San Pedro Quiatoni Zapotec", "zpg": "Guevea De Humboldt Zapotec", "zph": "Totomachapan Zapotec", "zpi": "Santa María Quiegolani Zapotec", "zpj": "Quiavicuzas Zapotec", "zpk": "Tlacolulita Zapotec", "zpl": "Lachixío Zapotec", "zpm": "Mixtepec Zapotec", "zpn": "Santa Inés Yatzechi Zapotec", "zpo": "Amatlán Zapotec", "zpp": "El Alto Zapotec", "zpq": "Zoogocho Zapotec", "zpr": "Santiago Xanica Zapotec", "zps": "Coatlán Zapotec", "zpt": "San Vicente Coatlán Zapotec", "zpu": "Yalálag Zapotec", "zpv": "Chichicapan Zapotec", "zpw": "Zaniza Zapotec", "zpx": "San Baltazar Loxicha Zapotec", "zpy": "Mazaltepec Zapotec", "zpz": "Texmelucan Zapotec", "zsr": "Southern Rincon Zapotec", "ztc": "Lachirioag Zapotec  (Retired 7/18/2007)", "zte": "Elotepec Zapotec", "ztg": "Xanaguía Zapotec", "ztl": "Lapaguía-Guivini Zapotec", "ztm": "San Agustín Mixtepec Zapotec", "ztn": "Santa Catarina Albarradas Zapotec", "ztp": "Loxicha Zapotec", "ztq": "Quioquitani-Quierí Zapotec", "zts": "Tilquiapan Zapotec", "ztt": "Tejalapan Zapotec", "ztu": "Güilá Zapotec", "ztx": "Zaachila Zapotec", "zty": "Yatee Zapotec"},
               "zha": {"ccx": "Northern Zhuang  (Retired 1/14/2008)", "ccy": "Southern Zhuang  (Retired 7/18/2007)", "zch": "Central Hongshuihe Zhuang", "zeh": "Eastern Hongshuihe Zhuang", "zgb": "Guibei Zhuang", "zgm": "Minz Zhuang", "zgn": "Guibian Zhuang", "zhd": "Dai Zhuang", "zhn": "Nong Zhuang", "zlj": "Liujiang Zhuang", "zln": "Lianshan Zhuang", "zlq": "Liuqian Zhuang", "zqe": "Qiubei Zhuang", "zyb": "Yongbei Zhuang", "zyg": "Yang Zhuang", "zyj": "Youjiang Zhuang", "zyn": "Yongnan Zhuang", "zzj": "Zuojiang Zhuang"},
               "zho": {"cdo": "Min Dong Chinese", "cjy": "Jinyu Chinese", "cmn": "Mandarin Chinese", "cpx": "Pu-Xian Chinese", "czh": "Huizhou Chinese", "czo": "Min Zhong Chinese", "gan": "Gan Chinese", "hak": "Hakka Chinese", "hsn": "Xiang Chinese", "lzh": "Literary Chinese", "mnp": "Min Bei Chinese", "nan": "Min Nan Chinese", "wuu": "Wu Chinese", "yue": "Yue Chinese"},
               "zza": {"diq": "Dimli (individual language)", "kiu": "Kirmanjki (individual language)"}}

def dead_to_dict(string):
  """
  Converts text copied from http://linguistlist.org/forms/langs/get-extinct.cfm
  to be initialised in a python dictionary format
  """
  lang_split = string.split('\n')
  lang_dict = []
  for x in lang_split:
    y = x.split('  ')
    lang_dict.append('"{}": "{}"'.format(y[1],y[0]))
  return '{' + ',\n        '.join(sorted(lang_dict)) + '}'

def macro_to_dict(string):
  """
  Converts text copied from http://www-01.sil.org/iso639-3/macrolanguages.asp
  to be initialised in a python dictionary format
  """
  macro_list = []
  member_list = []
  all_lines = string.split('\n')
  for line in all_lines:
    if line[0] == ' ':
      code, name = line[2:].strip().split('\t', 1)
      member_list[-1].append('"{}": "{}"'.format(code, name))
    else:
      macro_code, macro_name, code, name = line.split('\t')
      macro_list.append(macro_code)
      member_list.append(['"{}": "{}"'.format(code, name)])
  member_strings = ['"{}": {{{}}}'.format(macro_list[i], ', '.join(member_list[i])) for i in range(len(member_list))]
  return "{" + ",\n               ".join(member_strings) + "}"
